TEMPLATE = app
CONFIG += c++17
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

win32 {
    QMAKE_CFLAGS_RELEASE += -O2
    QMAKE_CXXFLAGS_RELEASE += -O2

    SDL_DEPS = $$PWD/deps/SDL2

    INCLUDEPATH += $$SDL_DEPS/SDL2-2.30.8/x86_64-w64-mingw32/include/SDL2
    INCLUDEPATH += $$SDL_DEPS/SDL2_image-2.8.2/x86_64-w64-mingw32/include/SDL2
    INCLUDEPATH += $$SDL_DEPS/SDL2_ttf-2.22.0/x86_64-w64-mingw32/include/SDL2
    INCLUDEPATH += $$SDL_DEPS/SDL2_mixer-2.8.0/x86_64-w64-mingw32/include/SDL2

    LIBS += -L$$SDL_DEPS/SDL2-2.30.8/x86_64-w64-mingw32/lib
    LIBS += -L$$SDL_DEPS/SDL2_ttf-2.22.0/x86_64-w64-mingw32/lib
    LIBS += -L$$SDL_DEPS/SDL2_mixer-2.8.0/x86_64-w64-mingw32/lib
    LIBS += -L$$SDL_DEPS/SDL2_image-2.8.2/x86_64-w64-mingw32/lib
} unix {
    QMAKE_CFLAGS_RELEASE -= -O2
    QMAKE_CFLAGS_RELEASE -= -O1
    QMAKE_CXXFLAGS_RELEASE -= -O2
    QMAKE_CXXFLAGS_RELEASE -= -O1
    QMAKE_CFLAGS_RELEASE += -m64 -O3
    QMAKE_CXXFLAGS_RELEASE += -m64 -O3

    QMAKE_LFLAGS += -no-pie

    LIBS += -lpthread
    LIBS += -L/usr/lib/x86_64-linux-gnu
    LIBS += -lstdc++fs
    LIBS += -lnoise
}
LIBS += -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer

SOURCES += \
        audio/god-sounds.cpp \
        audio/hero-sounds.cpp \
        audio/monster-sounds.cpp \
        audio/audio-device.cpp \
        audio/music.cpp \
        audio/music-vector.cpp \
        audio/sounds.cpp \
        audio/sound-vector.cpp \
        buildings/eaestheticsbuilding.cpp \
        buildings/eagorabase.cpp \
        buildings/eagoraspace.cpp \
        buildings/eanimalbuilding.cpp \
        buildings/earmory.cpp \
        buildings/earmsvendor.cpp \
        buildings/eartisansguild.cpp \
        buildings/eavailablebuildings.cpp \
        buildings/eavenue.cpp \
        buildings/ebibliotheke.cpp \
        buildings/eblackmarbleworkshop.cpp \
        buildings/ebuilding.cpp \
        buildings/ebuildingrenderer.cpp \
        buildings/ebuildingwithresource.cpp \
        buildings/ecardingshed.cpp \
        buildings/ecarrotfarm.cpp \
        buildings/echariotfactory.cpp \
        buildings/echariotvendor.cpp \
        buildings/ecollege.cpp \
        buildings/ecolumn.cpp \
        buildings/ecommonagora.cpp \
        buildings/ecorral.cpp \
        buildings/edairy.cpp \
        buildings/edramaschool.cpp \
        buildings/elite-housing.cpp \
        buildings/eelitehousingrenderer.cpp \
        buildings/eemployingbuilding.cpp \
        buildings/efarmbase.cpp \
        buildings/efishery.cpp \
        buildings/efleecevendor.cpp \
        buildings/efoodvendor.cpp \
        buildings/efoundry.cpp \
        buildings/efountain.cpp \
        buildings/egatehouse.cpp \
        buildings/egatehouserenderer.cpp \
        buildings/egranary.cpp \
        buildings/egrandagora.cpp \
        buildings/egrowerslodge.cpp \
        buildings/egymnasium.cpp \
        buildings/eheatgetters.cpp \
        buildings/eheroshall.cpp \
        buildings/ehippodrome.cpp \
        buildings/ehippodromepiece.cpp \
        buildings/ehorseranch.cpp \
        buildings/ehorseranchenclosure.cpp \
        buildings/ehorsevendor.cpp \
        buildings/ehospital.cpp \
        buildings/ehousebase.cpp \
        buildings/ehuntinglodge.cpp \
        buildings/einventorsworkshop.cpp \
        buildings/elaboratory.cpp \
        buildings/emaintenanceoffice.cpp \
        buildings/emasonryshop.cpp \
        buildings/emint.cpp \
        buildings/emonument.cpp \
        buildings/emuseum.cpp \
        buildings/eobservatory.cpp \
        buildings/eoilvendor.cpp \
        buildings/eolivepress.cpp \
        buildings/eonionfarm.cpp \
        buildings/epalace.cpp \
        buildings/epalacerenderer.cpp \
        buildings/epalacetile.cpp \
        buildings/epark.cpp \
        buildings/epatrolbuilding.cpp \
        buildings/epatrolbuildingbase.cpp \
        buildings/epatrolsourcebuilding.cpp \
        buildings/epatroltarget.cpp \
        buildings/epier.cpp \
        buildings/eplaceholder.cpp \
        buildings/epodium.cpp \
        buildings/eprocessingbuilding.cpp \
        buildings/erefinery.cpp \
        buildings/eresourcebuilding.cpp \
        buildings/eresourcebuildingbase.cpp \
        buildings/eresourcecollectbuilding.cpp \
        buildings/eresourcecollectbuildingbase.cpp \
        buildings/eroad.cpp \
        buildings/eruins.cpp \
        buildings/esculpturestudio.cpp \
        buildings/eshepherbuildingbase.cpp \
        buildings/small-house.cpp \
        buildings/estadium.cpp \
        buildings/estadiumrenderer.cpp \
        buildings/estoragebuilding.cpp \
        buildings/etaxoffice.cpp \
        buildings/etheater.cpp \
        buildings/etimbermill.cpp \
        buildings/etower.cpp \
        buildings/trade-post.cpp \
        buildings/etriremewharf.cpp \
        buildings/euniversity.cpp \
        buildings/eurchinquay.cpp \
        buildings/evendor.cpp \
        buildings/ewall.cpp \
        buildings/ewarehouse.cpp \
        buildings/ewarehousebase.cpp \
        buildings/ewatchpost.cpp \
        buildings/ewheatfarm.cpp \
        buildings/ewinery.cpp \
        buildings/ewinevendor.cpp \
        buildings/pyramids/epyramid.cpp \
        buildings/pyramids/epyramidaltar.cpp \
        buildings/pyramids/epyramidbuildingpart.cpp \
        buildings/pyramids/epyramidelement.cpp \
        buildings/pyramids/epyramidmonument.cpp \
        buildings/pyramids/epyramidmuseum.cpp \
        buildings/pyramids/epyramidobservatory.cpp \
        buildings/pyramids/epyramidstatue.cpp \
        buildings/pyramids/epyramidtemple.cpp \
        buildings/pyramids/epyramidtile.cpp \
        buildings/pyramids/epyramidtop.cpp \
        buildings/pyramids/epyramidwall.cpp \
        buildings/sanctuaries/eartemissanctuary.cpp \
        buildings/sanctuaries/ehephaestussanctuary.cpp \
        buildings/sanctuaries/esanctbuilding.cpp \
        buildings/sanctuaries/sanctuary.cpp \
        buildings/sanctuaries/esanctuaryblueprint.cpp \
        buildings/sanctuaries/estairsrenderer.cpp \
        engine/stamps/estampblueprint.cpp \
        engine/stamps/estamptool.cpp \
        engine/stamps/stamp-template-writer.cpp \
        buildings/sanctuaries/etemplealtarbuilding.cpp \
        buildings/sanctuaries/etemplebuilding.cpp \
        buildings/sanctuaries/etemplemonumentbuilding.cpp \
        buildings/sanctuaries/etemplestatuebuilding.cpp \
        buildings/sanctuaries/etempletilebuilding.cpp \
        buildings/sanctuaries/ezeussanctuary.cpp \
        characters/actions/eactionwithcomeback.cpp \
        characters/actions/eanimalaction.cpp \
        characters/actions/earcheraction.cpp \
        characters/actions/eartisanaction.cpp \
        characters/actions/eattackcityaction.cpp \
        characters/actions/ebuildaction.cpp \
        characters/actions/ecarttransporteraction.cpp \
        characters/actions/character-action.cpp \
        characters/actions/character-action-creator.cpp \
        characters/actions/character-action-function.cpp \
        characters/actions/character-action-function-creator.cpp \
        characters/actions/ecollectaction.cpp \
        characters/actions/ecollectresourceaction.cpp \
        characters/actions/ecomplexaction.cpp \
        characters/actions/edefendattackcityaction.cpp \
        characters/actions/edefendcityaction.cpp \
        characters/actions/edieaction.cpp \
        characters/actions/dionysus-follow-action.cpp \
        characters/actions/fight-action.cpp \
        characters/actions/fighting-action.cpp \
        characters/actions/fire-fighter-action.cpp \
        characters/actions/efollowaction.cpp \
        characters/actions/egodactcreator.cpp \
        characters/gods/actions/god-action.cpp \
        characters/gods/actions/egodattackaction.cpp \
        characters/gods/actions/egodmonsteraction.cpp \
        characters/gods/actions/egodvisitaction.cpp \
        characters/gods/actions/egodworshippedaction.cpp \
        characters/gods/actions/god-minion-action.cpp \
        characters/actions/egroweraction.cpp \
        characters/actions/eheroaction.cpp \
        characters/actions/ehuntaction.cpp \
        characters/actions/ekillcharacterfinishfail.cpp \
        characters/actions/monster-action.cpp \
        characters/actions/emoveaction.cpp \
        characters/actions/move-around-action.cpp \
        characters/actions/emovepathaction.cpp \
        characters/actions/emovetoaction.cpp \
        characters/actions/epatrolaction.cpp \
        characters/actions/epatrolmoveaction.cpp \
        characters/actions/ereplacecattleaction.cpp \
        characters/actions/esettleraction.cpp \
        characters/actions/shepherd-action.cpp \
        characters/actions/esickdisgruntledaction.cpp \
        characters/actions/soldier-action.cpp \
        characters/actions/etakecattleaction.cpp \
        characters/actions/trader-action.cpp \
        characters/actions/etriremeaction.cpp \
        characters/actions/ewaitaction.cpp \
        characters/actions/ewolfaction.cpp \
        characters/actions/godHelp/eaphroditehelpaction.cpp \
        characters/actions/godHelp/eapollohelpaction.cpp \
        characters/actions/godHelp/eareshelpaction.cpp \
        characters/actions/godHelp/eartemishelpaction.cpp \
        characters/actions/godHelp/eathenahelpaction.cpp \
        characters/actions/godHelp/eatlashelpaction.cpp \
        characters/actions/godHelp/edemeterhelpaction.cpp \
        characters/actions/godHelp/edionysushelpaction.cpp \
        characters/actions/godHelp/ehadeshelpaction.cpp \
        characters/actions/godHelp/ehephaestushelpaction.cpp \
        characters/actions/godHelp/eherahelpaction.cpp \
        characters/actions/godHelp/ehermeshelpaction.cpp \
        characters/actions/godHelp/eposeidonhelpaction.cpp \
        characters/actions/godHelp/eprovideresourcehelpaction.cpp \
        characters/actions/godHelp/ezeushelpaction.cpp \
        characters/actions/walkable/ehasnonbusyresourceobject.cpp \
        characters/actions/walkable/ehasresourceobject.cpp \
        characters/actions/walkable/ehasresourcewalkableobject.cpp \
        characters/actions/walkable/eobsticlehandler.cpp \
        characters/actions/walkable/erectwalkableobject.cpp \
        characters/actions/walkable/ewalkableobject.cpp \
        characters/actor.cpp \
        characters/eamazon.cpp \
        characters/animal.cpp \
        characters/archer.cpp \
        characters/earcherbase.cpp \
        characters/earcherposeidon.cpp \
        characters/eareswarrior.cpp \
        characters/eartisan.cpp \
        characters/astronomer.cpp \
        characters/eatlanteanarcher.cpp \
        characters/eatlanteanchariot.cpp \
        characters/eatlanteanhoplite.cpp \
        characters/ebasicpatroler.cpp \
        characters/eboar.cpp \
        characters/eboatbase.cpp \
        characters/bronze-miner.cpp \
        characters/butcher.cpp \
        characters/ecarttransporter.cpp \
        characters/ecattle.cpp \
        characters/ecentaurarcher.cpp \
        characters/ecentaurhorseman.cpp \
        characters/echaracter.cpp \
        characters/echaracterbase.cpp \
        characters/echaractercreator.cpp \
        characters/echariot.cpp \
        characters/echariotbase.cpp \
        characters/echariotposeidon.cpp \
        characters/competitor.cpp \
        characters/curator.cpp \
        characters/deer.cpp \
        characters/edisgruntled.cpp \
        characters/edomesticatedanimal.cpp \
        characters/edonkey.cpp \
        characters/eegyptianarcher.cpp \
        characters/eegyptianchariot.cpp \
        characters/eegyptianhoplite.cpp \
        characters/eelitecitizen.cpp \
        characters/eenemyboat.cpp \
        characters/eenlistedforces.cpp \
        characters/efightingcharacter.cpp \
        characters/efightingpatroler.cpp \
        characters/fire-fighter.cpp \
        characters/efishingboat.cpp \
        characters/egoat.cpp \
        characters/goatherd.cpp \
        characters/egreekhoplite.cpp \
        characters/egreekhorseman.cpp \
        characters/egreekrockthrower.cpp \
        characters/egrower.cpp \
        characters/gymnast.cpp \
        characters/healer.cpp \
        characters/ehomeless.cpp \
        characters/hoplite.cpp \
        characters/ehoplitebase.cpp \
        characters/ehopliteposeidon.cpp \
        characters/horse.cpp \
        characters/ehorseman.cpp \
        characters/ehorsemanbase.cpp \
        characters/ehunter.cpp \
        characters/inventor.cpp \
        characters/lumberjack.cpp \
        characters/emarbleminer.cpp \
        characters/emayanarcher.cpp \
        characters/emayanhoplite.cpp \
        characters/eoceanidhoplite.cpp \
        characters/eoceanidspearthrower.cpp \
        characters/eorichalcminer.cpp \
        characters/eox.cpp \
        characters/epeddler.cpp \
        characters/epersianarcher.cpp \
        characters/epersianhoplite.cpp \
        characters/epersianhorseman.cpp \
        characters/philosopher.cpp \
        characters/ephoenicianarcher.cpp \
        characters/ephoenicianhorseman.cpp \
        characters/eporter.cpp \
        characters/eracinghorse.cpp \
        characters/erangesoldier.cpp \
        characters/eresourcecollector.cpp \
        characters/eresourcecollectorbase.cpp \
        characters/erockthrower.cpp \
        characters/erockthrowerbase.cpp \
        characters/scholar.cpp \
        characters/esettler.cpp \
        characters/esheep.cpp \
        characters/shepherd.cpp \
        characters/eshepherdbase.cpp \
        characters/esick.cpp \
        characters/silver-miner.cpp \
        characters/esoldier.cpp \
        characters/soldier-banner.cpp \
        characters/espearthrowerbase.cpp \
        characters/tax-collector.cpp \
        characters/etradeboat.cpp \
        characters/trader.cpp \
        characters/etrailer.cpp \
        characters/etrireme.cpp \
        characters/etrojanhoplite.cpp \
        characters/etrojanhorseman.cpp \
        characters/etrojanspearthrower.cpp \
        characters/eurchingatherer.cpp \
        characters/watchman.cpp \
        characters/water-distributor.cpp \
        characters/ewildanimal.cpp \
        characters/wolf.cpp \
        characters/gods/eathena.cpp \
        characters/gods/ebasicgod.cpp \
        characters/gods/edemeter.cpp \
        characters/gods/edionysus.cpp \
        characters/gods/eextendedgod.cpp \
        characters/gods/egod.cpp \
        characters/gods/ehermes.cpp \
        characters/heroes/achilles.cpp \
        characters/heroes/ebasichero.cpp \
        characters/heroes/ehero.cpp \
        characters/monsters/ebasicmonster.cpp \
        characters/monsters/ecalydonianboar.cpp \
        characters/monsters/emonster.cpp \
        characters/monsters/ewatermonster.cpp \
        binary-image-loader.cpp \
        buildable-helpers.cpp \
        font-color.cpp \
        game-dir.cpp \
        e-invasion-handler.cpp \
        iterate-square.cpp \
        language.cpp \
        load-text-helper.cpp \
        main-window.cpp \
        message.cpp \
        messages.cpp \
        engine/ai/ai-building.cpp \
        engine/ai/ai-city-plan.cpp \
        engine/ai/ai-district.cpp \
        engine/boardData/ecityfinances.cpp \
        engine/boardData/eemploymentdata.cpp \
        engine/boardData/eheatmap.cpp \
        engine/boardData/eheatmapdivisor.cpp \
        engine/boardData/eheatmaptask.cpp \
        engine/boardData/ehusbandrydata.cpp \
        engine/boardData/epopulationdata.cpp \
        engine/board-city.cpp \
        engine/board-city-read.cpp \
        engine/BoardCitywrite.cpp \
        engine/e-board-player.cpp \
        engine/ecampaign.cpp \
        engine/ecampaignreadpak.cpp \
        engine/ecityid.cpp \
        engine/ecityrequest.cpp \
        engine/ecolonymonumentaction.cpp \
        engine/edate.cpp \
        engine/difficulty.cpp \
        engine/model-data.cpp \
        engine/vanilla-stats.cpp \
        engine/eemploymentdistributor.cpp \
        engine/eepisode.cpp \
        engine/eepisodegoal.cpp \
        engine/eeventtime.cpp \
        engine/efunctask.cpp \
        engine/e-game-board.cpp \
        engine/e-game-board-read.cpp \
        engine/egameboardwrite.cpp \
        engine/egameevents.cpp \
        engine/egifthelpers.cpp \
        engine/egodquest.cpp \
        engine/waypoint-move-path-task.cpp \
        engine/eknownendpathfinder.cpp \
        engine/emapgenerator.cpp \
        engine/emilitaryaid.cpp \
        engine/epathboard.cpp \
        engine/epathfinder.cpp \
        engine/epathfinderbase.cpp \
        engine/eplague.cpp \
        engine/eplannedaction.cpp \
        engine/eregrowforestaction.cpp \
        engine/ereinforcements.cpp \
        engine/eresourcetype.cpp \
        engine/etask.cpp \
        engine/etaxrate.cpp \
        engine/eterrain.cpp \
        engine/ethreadpool.cpp \
        engine/etile.cpp \
        engine/etilebase.cpp \
        engine/etileterrainpainter.cpp \
        engine/ewagerate.cpp \
        engine/world-board.cpp \
        engine/world-city.cpp \
        engine/eworldregion.cpp \
        engine/thread/ethreadboard.cpp \
        engine/thread/ethreadboardhandler.cpp \
        engine/thread/ethreadbuilding.cpp \
        engine/thread/ethreadcharacter.cpp \
        engine/thread/ethreaddata.cpp \
        engine/thread/ethreadtile.cpp \
        numbers.cpp \
        path-find-task.cpp \
        rand.cpp \
        settings.cpp \
        string-helpers.cpp \
        texture.cpp \
        texture-collection.cpp \
        tile-helper.cpp \
        vector-helpers.cpp \
        walkable-helpers.cpp \
        xml-parser.cpp \
        eng-parser.cpp \
        fileIO/building-reader.cpp \
        fileIO/building-writer.cpp \
        fileIO/read-stream.cpp \
        fileIO/write-stream.cpp \
        gameEvents/earmyeventbase.cpp \
        gameEvents/earmyreturnevent.cpp \
        gameEvents/eattackingcityeventvalue.cpp \
        gameEvents/ecitybecomesevent.cpp \
        gameEvents/ecityeventvalue.cpp \
        gameEvents/ecounteventvalue.cpp \
        gameEvents/edemandchangeevent.cpp \
        gameEvents/eearthquakeevent.cpp \
        gameEvents/eeconomicchangeevent.cpp \
        gameEvents/eeconomicmilitarychangeeventbase.cpp \
        gameEvents/eeventtrigger.cpp \
        gameEvents/egameevent.cpp \
        gameEvents/egiftfromevent.cpp \
        gameEvents/egifttoevent.cpp \
        gameEvents/egodattackevent.cpp \
        gameEvents/egoddisasterevent.cpp \
        gameEvents/egodeventvalue.cpp \
        gameEvents/egodquestevent.cpp \
        gameEvents/egodquesteventbase.cpp \
        gameEvents/egodquestfulfilledevent.cpp \
        gameEvents/egodreasoneventvalue.cpp \
        gameEvents/egodtraderesumesevent.cpp \
        gameEvents/egodvisitevent.cpp \
        gameEvents/einvasionevent.cpp \
        gameEvents/einvasionwarning.cpp \
        gameEvents/elandslideevent.cpp \
        gameEvents/elavaevent.cpp \
        gameEvents/emakerequestevent.cpp \
        gameEvents/emilitarychangeevent.cpp \
        gameEvents/emonstereventvalue.cpp \
        gameEvents/emonsterincityevent.cpp \
        gameEvents/emonsterinvasionevent.cpp \
        gameEvents/emonsterinvasioneventbase.cpp \
        gameEvents/emonsterseventvalue.cpp \
        gameEvents/emonsterunleashedevent.cpp \
        engine/tribute.cpp \
        gameEvents/receive-tribute-event.cpp \
        gameEvents/e-pay-tribute-event.cpp \
        gameEvents/eplayerconquestevent.cpp \
        gameEvents/eplayerconquesteventbase.cpp \
        gameEvents/eplayerraidevent.cpp \
        gameEvents/epointeventvalue.cpp \
        gameEvents/epricechangeevent.cpp \
        gameEvents/eraidresourceevent.cpp \
        gameEvents/requests/e-fulfill-request-event.cpp \
        gameEvents/requests/e-receive-request-type.cpp \
        gameEvents/ereinforcementsevent.cpp \
        gameEvents/erequestaidevent.cpp \
        gameEvents/erequeststrikeevent.cpp \
        gameEvents/eresourceeventvalue.cpp \
        gameEvents/eresourcegrantedeventbase.cpp \
        gameEvents/erivalarmyawayevent.cpp \
        gameEvents/esinklandevent.cpp \
        gameEvents/esupplychangeevent.cpp \
        gameEvents/esupplydemandchangeevent.cpp \
        gameEvents/etidalwaveevent.cpp \
        gameEvents/etradeopenupevent.cpp \
        gameEvents/etradeshutdownevent.cpp \
        gameEvents/etroopsrequestevent.cpp \
        gameEvents/etroopsrequestfulfilledevent.cpp \
        gameEvents/ewagechangeevent.cpp \
        gameEvents/ewarning.cpp \
        main.cpp \
        missiles/arrow-missile.cpp \
        missiles/arrow-spear-base.cpp \
        missiles/dust-missile.cpp \
        missiles/god-missile.cpp \
        missiles/lava-missile.cpp \
        missiles/missile.cpp \
        missiles/rock-missile.cpp \
        missiles/spear-missile.cpp \
        missiles/wave-missile.cpp \
        pak/epakhelpers.cpp \
        pak/gamefile.cpp \
        pak/pkwareinputstream.cpp \
        pak/qfile.cpp \
        pak/zeus-file.cpp \
        pointers/eobject.cpp \
        pointers/estdselfref.cpp \
        spawners/animal-spawner.cpp \
        spawners/banner.cpp \
        spawners/boar-spawner.cpp \
        spawners/deer-spawner.cpp \
        spawners/disaster-point.cpp \
        spawners/disembark-point.cpp \
        spawners/entry-point.cpp \
        spawners/exit-point.cpp \
        spawners/land-invasion-point.cpp \
        spawners/landslide-point.cpp \
        spawners/monster-point.cpp \
        spawners/sea-invasion-point.cpp \
        spawners/spawner.cpp \
        spawners/wolf-spawner.cpp \
        textures/beach-to-dry.cpp \
        textures/building-textures.cpp \
        textures/building-textures1.cpp \
        textures/building-textures2.cpp \
        textures/character-textures.cpp \
        textures/character-textures1.cpp \
        textures/character-textures2.cpp \
        textures/character-textures3.cpp \
        textures/character-textures4.cpp \
        textures/character-textures5.cpp \
        textures/character-textures6.cpp \
        textures/character-textures7.cpp \
        textures/character-textures8.cpp \
        textures/character-textures9.cpp \
        textures/destruction-textures.cpp \
        textures/fertile-to-dry.cpp \
        textures/forest-to-dry.cpp \
        textures/game-textures.cpp \
        textures/god-textures.cpp \
        textures/interface-textures.cpp \
        textures/lava-to-dry.cpp \
        textures/marble-tile.cpp \
        textures/marsh-to-dry.cpp \
        textures/park-texture.cpp \
        textures/sprite-loader.cpp \
        textures/stones-to-dry.cpp \
        textures/surrounding-terrain.cpp \
        textures/terrain-textures.cpp \
        textures/tile-to-texture.cpp \
        textures/varying-size-tex.cpp \
        textures/water-corner.cpp \
        textures/water-to-beach.cpp \
        textures/water-to-dry.cpp \
        textures/water-to-x.cpp \
        widgets/datawidgets/eadmindatawidget.cpp \
        widgets/datawidgets/eappealdatawidget.cpp \
        widgets/datawidgets/eculturedatawidget.cpp \
        widgets/datawidgets/edatawidget.cpp \
        widgets/datawidgets/eemploymentdatawidget.cpp \
        widgets/datawidgets/ehusbandrydatawidget.cpp \
        widgets/datawidgets/ehygienesafetydatawidget.cpp \
        widgets/datawidgets/emilitarydatawidget.cpp \
        widgets/datawidgets/emythologydatawidget.cpp \
        widgets/datawidgets/e-overview-data-widget.cpp \
        widgets/datawidgets/population-data-widget.cpp \
        widgets/datawidgets/esciencedatawidget.cpp \
        widgets/datawidgets/storage-sidebar-panel.cpp \
        widgets/datawidgets/eviewmodebutton.cpp \
        widgets/eacceptbutton.cpp \
        widgets/eactionlistwidget.cpp \
        widgets/earmymenu.cpp \
        widgets/ebasicbutton.cpp \
        widgets/ebitmapwidget.cpp \
        widgets/BoardCityswitchbutton.cpp \
        widgets/eboardsettingsmenu.cpp \
        widgets/ebuildbutton.cpp \
        widgets/ebuildingmode.cpp \
        widgets/ebuildingstoerase.cpp \
        widgets/ebuildwidget.cpp \
        widgets/ebutton.cpp \
        widgets/ebuttonbase.cpp \
        widgets/ebuttonslistwidget.cpp \
        widgets/ecancelbutton.cpp \
        widgets/echeckablebutton.cpp \
        widgets/echeckbox.cpp \
        widgets/echoosebutton.cpp \
        widgets/echoosecitydialog.cpp \
        widgets/echoosegameeditmenu.cpp \
        widgets/ecitybutton.cpp \
        widgets/ecityonboardselectionwidget.cpp \
        widgets/e-city-settings-widget.cpp \
        widgets/eclosabledialog.cpp \
        widgets/condition-settings-widget.cpp \
        widgets/edatebutton.cpp \
        widgets/edatewidget.cpp \
        widgets/district-conditions-widget.cpp \
        widgets/edownbutton.cpp \
        widgets/eeditormainmenu.cpp \
        widgets/eeditorsettingsmenu.cpp \
        widgets/eenlistforcesdialog.cpp \
        widgets/eepisodegoalselectionwidget.cpp \
        widgets/eepisodegoalwidget.cpp \
        widgets/eepisodeintroductionwidget.cpp \
        widgets/eepisodelostwidget.cpp \
        widgets/eepisodeswidget.cpp \
        widgets/eeventbackground.cpp \
        widgets/eeventselectionwidget.cpp \
        widgets/eeventwidget.cpp \
        widgets/eexclamationbutton.cpp \
        widgets/eloadgame.cpp \
        widgets/eflatbutton.cpp \
        widgets/efonts.cpp \
        widgets/eframedbutton.cpp \
        widgets/eframedbuttonwithicon.cpp \
        widgets/eframedlabel.cpp \
        widgets/eframedwidget.cpp \
        widgets/epopupwidget.cpp \
        widgets/efulfilldialog.cpp \
        widgets/egameloadingwidget.cpp \
        widgets/egamemainmenu.cpp \
        widgets/edifficultywidget.cpp \
        widgets/game-menu.cpp \
        widgets/game-menu-base.cpp \
        widgets/epierdebugwidget.cpp \
        widgets/game-widget.cpp \
        widgets/game-widget-build.cpp \
        widgets/GameWidgetevents.cpp \
        widgets/game-widget-info.cpp \
        widgets/paint/build-preview-paint.cpp \
        widgets/paint/build-preview-render.cpp \
        widgets/paint/game-widget-paint.cpp \
        widgets/paint/patrol-path-data.cpp \
        widgets/paint/sanctuary-preview.cpp \
        widgets/egiftdialog.cpp \
        widgets/egiftsizedialog.cpp \
        widgets/egodbutton.cpp \
        widgets/egodselectionwidget.cpp \
        widgets/ehelpbutton.cpp \
        widgets/eherobutton.cpp \
        widgets/elabel.cpp \
        widgets/elabelbase.cpp \
        widgets/elabeledwidget.cpp \
        widgets/eleftbutton.cpp \
        widgets/elineedit.cpp \
        widgets/elinewidget.cpp \
        widgets/eloadingwidget.cpp \
        widgets/emainmenu.cpp \
        widgets/emainmenubase.cpp \
        widgets/emainwidget.cpp \
        widgets/emenuloadingwidget.cpp \
        widgets/e-message-box.cpp \
        widgets/emessagewidget.cpp \
        widgets/emicrobutton.cpp \
        widgets/emilitarymoreinfowidget.cpp \
        widgets/eminimap.cpp \
        widgets/emonsterbutton.cpp \
        widgets/emonsterselectionwidget.cpp \
        widgets/emouseevent.cpp \
        widgets/emultilinelabel.cpp \
        widgets/emultipleselectionwidget.cpp \
        widgets/enamewidget.cpp \
        widgets/enumlineedit.cpp \
        widgets/enumlineeditwidget.cpp \
        widgets/eokbutton.cpp \
        widgets/epainter.cpp \
        widgets/eproceedbutton.cpp \
        widgets/eprogressbar.cpp \
        widgets/epyramidbutton.cpp \
        widgets/epyramidselectionwidget.cpp \
        widgets/epyramidwidget.cpp \
        widgets/equestionwidget.cpp \
        widgets/erequestdialog.cpp \
        widgets/eresolution.cpp \
        widgets/eresourcebutton.cpp \
        widgets/erightbutton.cpp \
        widgets/erosterofleaders.cpp \
        widgets/erotatebutton.cpp \
        widgets/escrollbar.cpp \
        widgets/escrollbuttonslist.cpp \
        widgets/elayouthelpers.cpp \
        widgets/escrollwidget.cpp \
        widgets/escrollwidgetcomplete.cpp \
        widgets/eselectcolonywidget.cpp \
        widgets/esmalldownbutton.cpp \
        widgets/esmallupbutton.cpp \
        widgets/espinbox.cpp \
        widgets/eswitchbutton.cpp \
        widgets/etabwidget.cpp \
        widgets/eterraineditmenu.cpp \
        widgets/etextscroller.cpp \
        widgets/etilepainter.cpp \
        widgets/etopbarwidget.cpp \
        widgets/etradeeditwidget.cpp \
        widgets/etriggerselectionwidget.cpp \
        widgets/etypebutton.cpp \
        widgets/eupbutton.cpp \
        widgets/evaluebutton.cpp \
        widgets/eventwidgets/eeventwidgetbase.cpp \
        widgets/eventwidgets/egodattackeventwidget.cpp \
        widgets/eventwidgets/egoddisastereventwidget.cpp \
        widgets/eventwidgets/egodquesteventwidget.cpp \
        widgets/eventwidgets/einvasioneventwidget.cpp \
        widgets/eviewmode.cpp \
        widgets/ewatertradewidget.cpp \
        widgets/ewidget.cpp \
        widgets/eworldgoodswidget.cpp \
        widgets/eworldmapwidget.cpp \
        widgets/eworldmenu.cpp \
        widgets/e-world-tribute-widget.cpp \
        widgets/eworldwidget.cpp \
        widgets/infowidgets/eagorainfowidget.cpp \
        widgets/infowidgets/echaracterinfowidget.cpp \
        widgets/infowidgets/common-house-info-widget.cpp \
        widgets/infowidgets/eemployingbuildinginfowidget.cpp \
        widgets/infowidgets/eheroshallinfowidget.cpp \
        widgets/infowidgets/ehippodromeinfowidget.cpp \
        widgets/infowidgets/einfowidget.cpp \
        widgets/infowidgets/esanctuaryinfowidget.cpp \
        widgets/infowidgets/estorageinfowidget.cpp \
        widgets/infowidgets/etradepostinfowidget.cpp \
        widgets/infowidgets/etriremewharfinfowidget.cpp \
        widgets/moreinfo/ecityfinanceswidget.cpp \
        widgets/moreinfo/eworkforceallocationwidget.cpp \
        widgets/moreinfo/storage-distribution-dialog.cpp

HEADERS += \
    audio/god-sounds.h \
    audio/hero-sounds.h \
    audio/monster-sounds.h \
    audio/audio-device.h \
    audio/music.h \
    audio/music-vector.h \
    audio/sounds.h \
    audio/sound-vector.h \
    buildings/allbuildings.h \
    buildings/eaestheticsbuilding.h \
    buildings/eagorabase.h \
    buildings/eagoraspace.h \
    buildings/eanimalbuilding.h \
    buildings/earmory.h \
    buildings/earmsvendor.h \
    buildings/eartisansguild.h \
    buildings/eavailablebuildings.h \
    buildings/eavenue.h \
    buildings/ebibliotheke.h \
    buildings/eblackmarbleworkshop.h \
    buildings/ebuilding.h \
    buildings/ebuildingrenderer.h \
    buildings/ebuildingwithresource.h \
    buildings/ecardingshed.h \
    buildings/ecarrotfarm.h \
    buildings/echariotfactory.h \
    buildings/echariotvendor.h \
    buildings/ecollege.h \
    buildings/ecolumn.h \
    buildings/ecommonagora.h \
    buildings/ecorral.h \
    buildings/edairy.h \
    buildings/edramaschool.h \
    buildings/elite-housing.h \
    buildings/eelitehousingrenderer.h \
    buildings/eemployingbuilding.h \
    buildings/efarmbase.h \
    buildings/efishery.h \
    buildings/efleecevendor.h \
    buildings/efoodvendor.h \
    buildings/efoundry.h \
    buildings/efountain.h \
    buildings/egatehouse.h \
    buildings/egatehouserenderer.h \
    buildings/egranary.h \
    buildings/egrandagora.h \
    buildings/egrowerslodge.h \
    buildings/egymnasium.h \
    buildings/eheatgetters.h \
    buildings/eheroshall.h \
    buildings/ehippodrome.h \
    buildings/ehippodromepiece.h \
    buildings/ehorseranch.h \
    buildings/ehorseranchenclosure.h \
    buildings/ehorsevendor.h \
    buildings/ehospital.h \
    buildings/ehousebase.h \
    buildings/ehuntinglodge.h \
    buildings/einventorsworkshop.h \
    buildings/elaboratory.h \
    buildings/emaintenanceoffice.h \
    buildings/emasonryshop.h \
    buildings/emint.h \
    buildings/emonument.h \
    buildings/emuseum.h \
    buildings/eobservatory.h \
    buildings/eoilvendor.h \
    buildings/eolivepress.h \
    buildings/eonionfarm.h \
    buildings/epalace.h \
    buildings/epalacerenderer.h \
    buildings/epalacetile.h \
    buildings/epark.h \
    buildings/epatrolbuilding.h \
    buildings/epatrolbuildingbase.h \
    buildings/epatrolsourcebuilding.h \
    buildings/epatroltarget.h \
    buildings/epier.h \
    buildings/eplaceholder.h \
    buildings/epodium.h \
    buildings/eprocessingbuilding.h \
    buildings/erefinery.h \
    buildings/eresourcebuilding.h \
    buildings/eresourcebuildingbase.h \
    buildings/eresourcecollectbuilding.h \
    buildings/eresourcecollectbuildingbase.h \
    buildings/eroad.h \
    buildings/eruins.h \
    buildings/esculpturestudio.h \
    buildings/eshepherbuildingbase.h \
    buildings/small-house.h \
    buildings/estadium.h \
    buildings/estadiumrenderer.h \
    buildings/estoragebuilding.h \
    buildings/etaxoffice.h \
    buildings/etheater.h \
    buildings/etimbermill.h \
    buildings/etower.h \
    buildings/trade-post.h \
    buildings/etriremewharf.h \
    buildings/euniversity.h \
    buildings/eurchinquay.h \
    buildings/evendor.h \
    buildings/ewall.h \
    buildings/ewarehouse.h \
    buildings/ewarehousebase.h \
    buildings/ewatchpost.h \
    buildings/ewheatfarm.h \
    buildings/ewinery.h \
    buildings/ewinevendor.h \
    buildings/pyramids/epyramid.h \
    buildings/pyramids/epyramidaltar.h \
    buildings/pyramids/epyramidbuildingpart.h \
    buildings/pyramids/epyramidelement.h \
    buildings/pyramids/epyramidmonument.h \
    buildings/pyramids/epyramidmuseum.h \
    buildings/pyramids/epyramidobservatory.h \
    buildings/pyramids/epyramidstatue.h \
    buildings/pyramids/epyramidtemple.h \
    buildings/pyramids/epyramidtile.h \
    buildings/pyramids/epyramidtop.h \
    buildings/pyramids/epyramidwall.h \
    buildings/sanctuaries/eartemissanctuary.h \
    buildings/sanctuaries/ehephaestussanctuary.h \
    buildings/sanctuaries/esanctbuilding.h \
    buildings/sanctuaries/sanctuary.h \
    buildings/sanctuaries/esanctuaryblueprint.h \
    buildings/sanctuaries/estairsrenderer.h \
    engine/stamps/estampblueprint.h \
    engine/stamps/estamptool.h \
    engine/stamps/stamp-template-writer.h \
    buildings/sanctuaries/etemplealtarbuilding.h \
    buildings/sanctuaries/etemplebuilding.h \
    buildings/sanctuaries/etemplemonumentbuilding.h \
    buildings/sanctuaries/etemplestatuebuilding.h \
    buildings/sanctuaries/etempletilebuilding.h \
    buildings/sanctuaries/ezeussanctuary.h \
    characters/actions/eactionwithcomeback.h \
    characters/actions/eanimalaction.h \
    characters/actions/earcheraction.h \
    characters/actions/eartisanaction.h \
    characters/actions/eattackcityaction.h \
    characters/actions/ebuildaction.h \
    characters/actions/ecarttransporteraction.h \
    characters/actions/character-action.h \
    characters/actions/character-action-function.h \
    characters/actions/echaracteractiontype.h \
    characters/actions/ecollectaction.h \
    characters/actions/ecollectresourceaction.h \
    characters/actions/ecomplexaction.h \
    characters/actions/edefendattackcityaction.h \
    characters/actions/edefendcityaction.h \
    characters/actions/edieaction.h \
    characters/actions/dionysus-follow-action.h \
    characters/actions/fight-action.h \
    characters/actions/fighting-action.h \
    characters/actions/fire-fighter-action.h \
    characters/actions/efollowaction.h \
    characters/gods/actions/god-action.h \
    characters/gods/actions/egodattackaction.h \
    characters/gods/actions/egodmonsteraction.h \
    characters/gods/actions/egodvisitaction.h \
    characters/gods/actions/egodworshippedaction.h \
    characters/gods/actions/god-minion-action.h \
    characters/actions/egroweraction.h \
    characters/actions/eheroaction.h \
    characters/actions/ehuntaction.h \
    characters/actions/ekillcharacterfinishfail.h \
    characters/actions/monster-action.h \
    characters/actions/emoveaction.h \
    characters/actions/move-around-action.h \
    characters/actions/emovepathaction.h \
    characters/actions/emovetoaction.h \
    characters/actions/epatrolaction.h \
    characters/actions/epatrolmoveaction.h \
    characters/actions/ereplacecattleaction.h \
    characters/actions/esettleraction.h \
    characters/actions/shepherd-action.h \
    characters/actions/esickdisgruntledaction.h \
    characters/actions/soldier-action.h \
    characters/actions/etakecattleaction.h \
    characters/actions/trader-action.h \
    characters/actions/etriremeaction.h \
    characters/actions/ewaitaction.h \
    characters/actions/ewolfaction.h \
    characters/actions/godHelp/eaphroditehelpaction.h \
    characters/actions/godHelp/eapollohelpaction.h \
    characters/actions/godHelp/eareshelpaction.h \
    characters/actions/godHelp/eartemishelpaction.h \
    characters/actions/godHelp/eathenahelpaction.h \
    characters/actions/godHelp/eatlashelpaction.h \
    characters/actions/godHelp/edemeterhelpaction.h \
    characters/actions/godHelp/edionysushelpaction.h \
    characters/actions/godHelp/ehadeshelpaction.h \
    characters/actions/godHelp/ehephaestushelpaction.h \
    characters/actions/godHelp/eherahelpaction.h \
    characters/actions/godHelp/ehermeshelpaction.h \
    characters/actions/godHelp/eposeidonhelpaction.h \
    characters/actions/godHelp/eprovideresourcehelpaction.h \
    characters/actions/godHelp/ezeushelpaction.h \
    characters/actions/walkable/ehasnonbusyresourceobject.h \
    characters/actions/walkable/ehasresourceobject.h \
    characters/actions/walkable/ehasresourcewalkableobject.h \
    characters/actions/walkable/eobsticlehandler.h \
    characters/actions/walkable/erectwalkableobject.h \
    characters/actions/walkable/ewalkableobject.h \
    characters/actor.h \
    characters/eamazon.h \
    characters/animal.h \
    characters/archer.h \
    characters/earcherbase.h \
    characters/earcherposeidon.h \
    characters/eareswarrior.h \
    characters/eartisan.h \
    characters/astronomer.h \
    characters/eatlanteanarcher.h \
    characters/eatlanteanchariot.h \
    characters/eatlanteanhoplite.h \
    characters/ebasicpatroler.h \
    characters/eboar.h \
    characters/eboatbase.h \
    characters/bronze-miner.h \
    characters/butcher.h \
    characters/ecarttransporter.h \
    characters/ecattle.h \
    characters/ecentaurarcher.h \
    characters/ecentaurhorseman.h \
    characters/echaracter.h \
    characters/echaracterbase.h \
    characters/echariot.h \
    characters/echariotbase.h \
    characters/echariotposeidon.h \
    characters/competitor.h \
    characters/curator.h \
    characters/deer.h \
    characters/edisgruntled.h \
    characters/edomesticatedanimal.h \
    characters/edonkey.h \
    characters/eegyptianarcher.h \
    characters/eegyptianchariot.h \
    characters/eegyptianhoplite.h \
    characters/eelitecitizen.h \
    characters/eenemyboat.h \
    characters/eenlistedforces.h \
    characters/efightingcharacter.h \
    characters/efightingpatroler.h \
    characters/fire-fighter.h \
    characters/efishingboat.h \
    characters/egoat.h \
    characters/goatherd.h \
    characters/egreekhoplite.h \
    characters/egreekhorseman.h \
    characters/egreekrockthrower.h \
    characters/egrower.h \
    characters/gymnast.h \
    characters/healer.h \
    characters/ehomeless.h \
    characters/hoplite.h \
    characters/ehoplitebase.h \
    characters/ehopliteposeidon.h \
    characters/horse.h \
    characters/ehorseman.h \
    characters/ehorsemanbase.h \
    characters/ehunter.h \
    characters/inventor.h \
    characters/lumberjack.h \
    characters/emarbleminer.h \
    characters/emayanarcher.h \
    characters/emayanhoplite.h \
    characters/eoceanidhoplite.h \
    characters/eoceanidspearthrower.h \
    characters/eorichalcminer.h \
    characters/eox.h \
    characters/epeddler.h \
    characters/epersianarcher.h \
    characters/epersianhoplite.h \
    characters/epersianhorseman.h \
    characters/philosopher.h \
    characters/ephoenicianarcher.h \
    characters/ephoenicianhorseman.h \
    characters/eporter.h \
    characters/eracinghorse.h \
    characters/erangesoldier.h \
    characters/eresourcecollector.h \
    characters/eresourcecollectorbase.h \
    characters/erockthrower.h \
    characters/erockthrowerbase.h \
    characters/scholar.h \
    characters/esettler.h \
    characters/esheep.h \
    characters/shepherd.h \
    characters/eshepherdbase.h \
    characters/esick.h \
    characters/silver-miner.h \
    characters/esoldier.h \
    characters/soldier-banner.h \
    characters/espearthrowerbase.h \
    characters/tax-collector.h \
    characters/etradeboat.h \
    characters/trader.h \
    characters/etrailer.h \
    characters/etrireme.h \
    characters/etrojanhoplite.h \
    characters/etrojanhorseman.h \
    characters/etrojanspearthrower.h \
    characters/eurchingatherer.h \
    characters/watchman.h \
    characters/water-distributor.h \
    characters/ewildanimal.h \
    characters/wolf.h \
    characters/gods/eathena.h \
    characters/gods/ebasicgod.h \
    characters/gods/edemeter.h \
    characters/gods/edionysus.h \
    characters/gods/eextendedgod.h \
    characters/gods/egod.h \
    characters/gods/egodtype.h \
    characters/gods/ehermes.h \
    characters/heroes/achilles.h \
    characters/heroes/ebasichero.h \
    characters/heroes/ehero.h \
    characters/monsters/ebasicmonster.h \
    characters/monsters/ecalydonianboar.h \
    characters/monsters/emonster.h \
    characters/monsters/emonstertype.h \
    characters/monsters/ewatermonster.h \
    binary-image-loader.h \
    buildable-helpers.h \
    font-color.h \
    game-dir.h \
    e-invasion-handler.h \
    iterate-square.h \
    language.h \
   game-limits.h \
    load-text-helper.h \
    main-window.h \
    message.h \
    messages.h \
    engine/ai/ai-building.h \
    engine/ai/ai-city-plan.h \
    engine/ai/ai-district.h \
    engine/boardData/ecityfinances.h \
    engine/boardData/eemploymentdata.h \
    engine/boardData/eheatmap.h \
    engine/boardData/eheatmapdivisor.h \
    engine/boardData/eheatmaptask.h \
    engine/boardData/ehusbandrydata.h \
    engine/boardData/epopulationdata.h \
    engine/board-city.h \
    engine/e-board-player.h \
    engine/ecampaign.h \
    engine/ecityid.h \
    engine/ecityrequest.h \
    engine/ecolonymonumentaction.h \
    engine/edate.h \
    engine/difficulty.h \
    engine/model-data.h \
    engine/vanilla-stats.h \
    engine/tribute.h \
    engine/eemploymentdistributor.h \
    engine/eepisode.h \
    engine/eepisodegoal.h \
    engine/eevent.h \
    engine/eeventdata.h \
    engine/eeventtime.h \
    engine/efunctask.h \
    engine/e-game-board.h \
    engine/egameevents.h \
    engine/egifthelpers.h \
    engine/egodquest.h \
    engine/waypoint-move-path-task.h \
    engine/eknownendpathfinder.h \
    engine/emapgenerator.h \
    engine/emessageeventtype.h \
    engine/emilitaryaid.h \
    engine/emovedirection.h \
    engine/eorientation.h \
    engine/epathboard.h \
    engine/epathfinder.h \
    engine/epathfinderbase.h \
    engine/patrol-waypoint.h \
    engine/eplague.h \
    engine/eplannedaction.h \
    engine/eprovide.h \
    engine/eregrowforestaction.h \
    engine/ereinforcements.h \
    engine/eresourcetype.h \
    engine/estaterelevance.h \
    engine/etask.h \
    engine/etaxrate.h \
    engine/eterrain.h \
    engine/ethreadpool.h \
    engine/etile.h \
    engine/etilebase.h \
    engine/etileterrainpainter.h \
    engine/ewagerate.h \
    engine/world-board.h \
    engine/world-city.h \
    engine/eworlddirection.h \
    engine/eworldregion.h \
    engine/thread/ethreadboard.h \
    engine/thread/ethreadboardhandler.h \
    engine/thread/ethreadbuilding.h \
    engine/thread/ethreadcharacter.h \
    engine/thread/ethreaddata.h \
    engine/thread/ethreadtile.h \
    numbers.h \
    overlay.h \
    path-find-task.h \
    rand.h \
    settings.h \
    split-binary.h \
    string-helpers.h \
    texture.h \
    texture-collection.h \
    tile-helper.h \
    vector-helpers.h \
    walkable-helpers.h \
    xml-parser.h \
    eng-parser.h \
    fileIO/building-reader.h \
    fileIO/building-writer.h \
    fileIO/read-stream.h \
    fileIO/streams.h \
    fileIO/write-stream.h \
    gameEvents/earmyeventbase.h \
    gameEvents/earmyreturnevent.h \
    gameEvents/eattackingcityeventvalue.h \
    gameEvents/ecitybecomesevent.h \
    gameEvents/ecityeventvalue.h \
    gameEvents/ecounteventvalue.h \
    gameEvents/edemandchangeevent.h \
    gameEvents/eearthquakeevent.h \
    gameEvents/eeconomicchangeevent.h \
    gameEvents/eeconomicmilitarychangeeventbase.h \
    gameEvents/eeventtrigger.h \
    gameEvents/egameevent.h \
    gameEvents/egiftfromevent.h \
    gameEvents/egifttoevent.h \
    gameEvents/egodattackevent.h \
    gameEvents/egoddisasterevent.h \
    gameEvents/egodeventvalue.h \
    gameEvents/egodquestevent.h \
    gameEvents/egodquesteventbase.h \
    gameEvents/egodquestfulfilledevent.h \
    gameEvents/egodreasoneventvalue.h \
    gameEvents/egodtraderesumesevent.h \
    gameEvents/egodvisitevent.h \
    gameEvents/einvasionevent.h \
    gameEvents/einvasionwarning.h \
    gameEvents/elandslideevent.h \
    gameEvents/elavaevent.h \
    gameEvents/emakerequestevent.h \
    gameEvents/emilitarychangeevent.h \
    gameEvents/emonstereventvalue.h \
    gameEvents/emonsterincityevent.h \
    gameEvents/emonsterinvasionevent.h \
    gameEvents/emonsterinvasioneventbase.h \
    gameEvents/emonsterseventvalue.h \
    gameEvents/emonsterunleashedevent.h \
    gameEvents/receive-tribute-event.h \
    gameEvents/e-pay-tribute-event.h \
    gameEvents/eplayerconquestevent.h \
    gameEvents/eplayerconquesteventbase.h \
    gameEvents/eplayerraidevent.h \
    gameEvents/epointeventvalue.h \
    gameEvents/epricechangeevent.h \
    gameEvents/eraidresourceevent.h \
    gameEvents/requests/e-fulfill-request-event.h \
    gameEvents/requests/e-receive-request-type.h \
    gameEvents/ereinforcementsevent.h \
    gameEvents/erequestaidevent.h \
    gameEvents/erequeststrikeevent.h \
    gameEvents/eresourceeventvalue.h \
    gameEvents/eresourcegrantedeventbase.h \
    gameEvents/erivalarmyawayevent.h \
    gameEvents/esinklandevent.h \
    gameEvents/esupplychangeevent.h \
    gameEvents/esupplydemandchangeevent.h \
    gameEvents/etidalwaveevent.h \
    gameEvents/etradeopenupevent.h \
    gameEvents/etradeshutdownevent.h \
    gameEvents/etroopsrequestevent.h \
    gameEvents/etroopsrequestfulfilledevent.h \
    gameEvents/ewagechangeevent.h \
    gameEvents/ewarning.h \
    missiles/arrow-missile.h \
    missiles/arrow-spear-base.h \
    missiles/dust-missile.h \
    missiles/god-missile.h \
    missiles/lava-missile.h \
    missiles/missile.h \
    missiles/rock-missile.h \
    missiles/spear-missile.h \
    missiles/wave-missile.h \
    offsets/PoseidonImps.h \
    offsets/PoseidonImps2.h \
    offsets/Poseidon_Atalanta.h \
    offsets/Poseidon_Atlantean.h \
    offsets/Poseidon_Atlas.h \
    offsets/Poseidon_Bellerophon.h \
    offsets/Poseidon_Chimera.h \
    offsets/Poseidon_Echidna.h \
    offsets/Poseidon_Egyptian.h \
    offsets/Poseidon_Harpie.h \
    offsets/Poseidon_Hera.h \
    offsets/Poseidon_Mayan.h \
    offsets/Poseidon_Oceanid.h \
    offsets/Poseidon_Phoenician.h \
    offsets/Poseidon_Sphinx.h \
    offsets/SprAmbient.h \
    offsets/SprMain.h \
    offsets/Zeus_Aphrodite.h \
    offsets/Zeus_Apollo.h \
    offsets/Zeus_Ares.h \
    offsets/Zeus_AresWarriors.h \
    offsets/Zeus_Artemis.h \
    offsets/Zeus_Athena.h \
    offsets/Zeus_Demeter.h \
    offsets/Zeus_Dionysus.h \
    offsets/Zeus_Greek.h \
    offsets/Zeus_Hades.h \
    offsets/Zeus_Hephaestus.h \
    offsets/Zeus_Hermes.h \
    offsets/Zeus_Poseidon.h \
    offsets/Zeus_Zeus.h \
    offsets/Zeus_amazon.h \
    offsets/Zeus_centaur.h \
    offsets/Zeus_persian.h \
    offsets/Zeus_trojan.h \
    offsets/destruction.h \
    offsets/zeus_achilles.h \
    offsets/zeus_calydonianboar.h \
    offsets/zeus_cerberus.h \
    offsets/zeus_cyclops.h \
    offsets/zeus_dragon.h \
    offsets/zeus_hector.h \
    offsets/zeus_heracles.h \
    offsets/zeus_hydra.h \
    offsets/zeus_jason.h \
    offsets/zeus_kraken.h \
    offsets/zeus_maenads.h \
    offsets/zeus_medusa.h \
    offsets/zeus_minotaur.h \
    offsets/zeus_odysseus.h \
    offsets/zeus_perseus.h \
    offsets/zeus_satyr.h \
    offsets/zeus_scylla.h \
    offsets/zeus_talos.h \
    offsets/zeus_theseus.h \
    pak/epakhelpers.h \
    pak/gamefile.h \
    pak/grid.h \
    pak/pkwareinputstream.h \
    pak/qfile.h \
    pak/zeusfile.h \
    pointers/eobject.h \
    pointers/eobject.h \
    pointers/estdpointer.h \
    pointers/estdselfref.h \
    spawners/animal-spawner.h \
    spawners/banner.h \
    spawners/boar-spawner.h \
    spawners/deer-spawner.h \
    spawners/disaster-point.h \
    spawners/disembark-point.h \
    spawners/entry-point.h \
    spawners/exit-point.h \
    spawners/land-invasion-point.h \
    spawners/landslide-point.h \
    spawners/monster-point.h \
    spawners/sea-invasion-point.h \
    spawners/spawner.h \
    spawners/wolf-spawner.h \
    spriteData/achilles30.h \
    spriteData/actor30.h \
    spriteData/agora30.h \
    spriteData/altarBullOverlay30.h \
    spriteData/altarGoodsOverlay30.h \
    spriteData/altarSheepOverlay30.h \
    spriteData/amazonArcher30.h \
    spriteData/amazonSpear30.h \
    spriteData/aphrodite30.h \
    spriteData/aphroditeStatue30.h \
    spriteData/apollo30.h \
    spriteData/apolloStatue30.h \
    spriteData/archer30.h \
    spriteData/archerPoseidon30.h \
    spriteData/ares30.h \
    spriteData/aresStatue30.h \
    spriteData/aresWarrior30.h \
    spriteData/armory30.h \
    spriteData/armsVendor30.h \
    spriteData/arrow30.h \
    spriteData/artemis30.h \
    spriteData/artemisStatue30.h \
    spriteData/artisan30.h \
    spriteData/artisansGuild30.h \
    spriteData/astronomer30.h \
    spriteData/atalanta30.h \
    spriteData/athena30.h \
    spriteData/athenaStatue30.h \
    spriteData/atlanteanArcher30.h \
    spriteData/atlanteanChariot30.h \
    spriteData/atlanteanHoplite30.h \
    spriteData/atlas30.h \
    spriteData/atlasStatue30.h \
    spriteData/avenue30.h \
    spriteData/banners30.h \
    spriteData/baths30.h \
    spriteData/bellerophon30.h \
    spriteData/bench30.h \
    spriteData/bibliotheke30.h \
    spriteData/birdBath30.h \
    spriteData/blackArrow30.h \
    spriteData/blackMarbleTerrain30.h \
    spriteData/blackMarbleTrailer30.h \
    spriteData/blackMarbleWorkshop30.h \
    spriteData/blackSpear30.h \
    spriteData/blankStatue30.h \
    spriteData/bless30.h \
    spriteData/blessed30.h \
    spriteData/boar30.h \
    spriteData/bridge30.h \
    spriteData/bronzeMiner30.h \
    spriteData/bull30.h \
    spriteData/butcher30.h \
    spriteData/calydonianBoar30.h \
    spriteData/cardingShed30.h \
    spriteData/cart30.h \
    spriteData/cattle130.h \
    spriteData/cattle230.h \
    spriteData/cattle330.h \
    spriteData/centaurArcher30.h \
    spriteData/centaurHorseman30.h \
    spriteData/cerberus30.h \
    spriteData/chariot30.h \
    spriteData/chariotFactory30.h \
    spriteData/chariotFactoryHorses30.h \
    spriteData/chariotFactoryOverlay130.h \
    spriteData/chariotPoseidon30.h \
    spriteData/chariotVendor30.h \
    spriteData/chariotVendorCharacter30.h \
    spriteData/chariotVendorOverlay30.h \
    spriteData/chimera30.h \
    spriteData/college30.h \
    spriteData/columns30.h \
    spriteData/commemorative30.h \
    spriteData/commonHouse30.h \
    spriteData/competitor30.h \
    spriteData/corral30.h \
    spriteData/corralCattleOverlay30.h \
    spriteData/corralProcessingOverlay30.h \
    spriteData/curator30.h \
    spriteData/curse30.h \
    spriteData/cursed30.h \
    spriteData/cyclops30.h \
    spriteData/dairy30.h \
    spriteData/deer30.h \
    spriteData/deerHunter30.h \
    spriteData/deerTop30.h \
    spriteData/demeter30.h \
    spriteData/demeterStatue30.h \
    spriteData/dionysus30.h \
    spriteData/dionysusStatue30.h \
    spriteData/disgruntled30.h \
    spriteData/dolphinSculpture30.h \
    spriteData/donkey30.h \
    spriteData/dragon30.h \
    spriteData/dramaSchool30.h \
    spriteData/dust30.h \
    spriteData/echidna30.h \
    spriteData/egyptianArcher30.h \
    spriteData/egyptianChariot30.h \
    spriteData/egyptianHoplite30.h \
    spriteData/elephant30.h \
    spriteData/eliteCitizen30.h \
    spriteData/eliteHouse30.h \
    spriteData/empireBits30.h \
    spriteData/empireFigures30.h \
    spriteData/enemyBoat30.h \
    spriteData/espritedata.h \
    spriteData/fire130.h \
    spriteData/fireFighter30.h \
    spriteData/fish30.h \
    spriteData/fishPond30.h \
    spriteData/fishPondOverlay30.h \
    spriteData/fishery30.h \
    spriteData/fisheryBoatBuilding30.h \
    spriteData/fisheryOverlay30.h \
    spriteData/fisheryUnpackingOverlay30.h \
    spriteData/fishingBoat30.h \
    spriteData/fleeceVendor30.h \
    spriteData/fleecedSheep30.h \
    spriteData/flowerGarden30.h \
    spriteData/foodCart30.h \
    spriteData/foodVendor30.h \
    spriteData/foundry30.h \
    spriteData/fountain30.h \
    spriteData/gatehouseAndTower30.h \
    spriteData/gazebo30.h \
    spriteData/goat30.h \
    spriteData/goatherd30.h \
    spriteData/godBlueArrow30.h \
    spriteData/godBlueMissile30.h \
    spriteData/godGreenMissile30.h \
    spriteData/godOrangeArrow30.h \
    spriteData/godOrangeMissile30.h \
    spriteData/godPinkMissile30.h \
    spriteData/godPurpleMissile30.h \
    spriteData/godRedMissile30.h \
    spriteData/granary30.h \
    spriteData/greekHoplite30.h \
    spriteData/greekHorseman30.h \
    spriteData/greekRockThrower30.h \
    spriteData/grower30.h \
    spriteData/growersLodge30.h \
    spriteData/gymnasium30.h \
    spriteData/gymnast30.h \
    spriteData/hades30.h \
    spriteData/hadesStatue30.h \
    spriteData/harpie30.h \
    spriteData/healer30.h \
    spriteData/hector30.h \
    spriteData/hedgeMaze30.h \
    spriteData/hephaestus30.h \
    spriteData/hephaestusStatue30.h \
    spriteData/hera30.h \
    spriteData/heraStatue30.h \
    spriteData/heracles30.h \
    spriteData/hermes30.h \
    spriteData/hermesStatue30.h \
    spriteData/hippodrome30.h \
    spriteData/hippodromeBeer30.h \
    spriteData/hippodromeFeces30.h \
    spriteData/hippodromeFinish30.h \
    spriteData/hippodromeHorse130.h \
    spriteData/hippodromeHorse230.h \
    spriteData/hippodromeHorse330.h \
    spriteData/hippodromeHorse430.h \
    spriteData/hippodromeHotDogs30.h \
    spriteData/hippodromeSpectators30.h \
    spriteData/hippodromeStand30.h \
    spriteData/homeless30.h \
    spriteData/hoplite30.h \
    spriteData/hoplitePoseidon30.h \
    spriteData/horse30.h \
    spriteData/horseRanch30.h \
    spriteData/horseRanchEnclosure30.h \
    spriteData/horseVendor30.h \
    spriteData/horseman30.h \
    spriteData/hospital30.h \
    spriteData/hunter30.h \
    spriteData/huntingLodge30.h \
    spriteData/hydra30.h \
    spriteData/interfaceBanners30.h \
    spriteData/interfaceMapEditor30.h \
    spriteData/interfaceNewBbuttons30.h \
    spriteData/interfaceNewParts30.h \
    spriteData/interfaceParts30.h \
    spriteData/interfaceRadar30.h \
    spriteData/interfaceSprites30.h \
    spriteData/interfaceWorldSide30.h \
    spriteData/interface_stor_bays30.h \
    spriteData/inventor30.h \
    spriteData/inventorsWorkshop30.h \
    spriteData/jason30.h \
    spriteData/kraken30.h \
    spriteData/laboratory30.h \
    spriteData/lava30.h \
    spriteData/lumberjack30.h \
    spriteData/maenads30.h \
    spriteData/maintenanceOffice30.h \
    spriteData/marbleMiner30.h \
    spriteData/masonryShop30.h \
    spriteData/masonryShopOverlays30.h \
    spriteData/mayanArcher30.h \
    spriteData/mayanHoplite30.h \
    spriteData/medusa30.h \
    spriteData/minotaur30.h \
    spriteData/mint30.h \
    spriteData/monsterMissile30.h \
    spriteData/mun_Palace30.h \
    spriteData/museum30.h \
    spriteData/nudeSheep30.h \
    spriteData/observatory30.h \
    spriteData/oceanidHoplite30.h \
    spriteData/oceanidSpearthrower30.h \
    spriteData/odysseus30.h \
    spriteData/oilVendor30.h \
    spriteData/olivePress30.h \
    spriteData/oliveTree30.h \
    spriteData/orangeTender30.h \
    spriteData/orangeTendersLodge30.h \
    spriteData/orangesCart30.h \
    spriteData/orichalcArcher30.h \
    spriteData/orichalcCart30.h \
    spriteData/orichalcExplosion30.h \
    spriteData/orichalcMiner30.h \
    spriteData/orichalcMissile30.h \
    spriteData/orichalcTerrain30.h \
    spriteData/orichalcTowerOverlay30.h \
    spriteData/orrery30.h \
    spriteData/ox30.h \
    spriteData/oxHandler30.h \
    spriteData/palaceOverlay30.h \
    spriteData/palaceTiles30.h \
    spriteData/paneling30.h \
    spriteData/park30.h \
    spriteData/peddler30.h \
    spriteData/perseus30.h \
    spriteData/persianArcher30.h \
    spriteData/persianHoplite30.h \
    spriteData/persianHorseman30.h \
    spriteData/philosopher30.h \
    spriteData/phoenicianArcher30.h \
    spriteData/phoenicianHorseman30.h \
    spriteData/pier130.h \
    spriteData/pier230.h \
    spriteData/plague30.h \
    spriteData/plantation30.h \
    spriteData/podium30.h \
    spriteData/porter30.h \
    spriteData/poseidon30.h \
    spriteData/poseidonBannerTops30.h \
    spriteData/poseidonBridge30.h \
    spriteData/poseidonCampaign130.h \
    spriteData/poseidonCampaign230.h \
    spriteData/poseidonCampaign330.h \
    spriteData/poseidonCampaign430.h \
    spriteData/poseidonCampaign530.h \
    spriteData/poseidonCampaign630.h \
    spriteData/poseidonCommonHouse30.h \
    spriteData/poseidonEliteHouse30.h \
    spriteData/poseidonHerosHall230.h \
    spriteData/poseidonHerosHall30.h \
    spriteData/poseidonInterface30.h \
    spriteData/poseidonPortraits30.h \
    spriteData/poseidonPyramid230.h \
    spriteData/poseidonPyramid30.h \
    spriteData/poseidonQuestButtons30.h \
    spriteData/poseidonSanctuary30.h \
    spriteData/poseidonStatue30.h \
    spriteData/poseidonStatues130.h \
    spriteData/poseidonStatues230.h \
    spriteData/poseidonTowerArcher30.h \
    spriteData/poseidonTrees30.h \
    spriteData/poseidonUnits30.h \
    spriteData/priest30.h \
    spriteData/refinery30.h \
    spriteData/roadblock30.h \
    spriteData/rock30.h \
    spriteData/rockThrower30.h \
    spriteData/sanctuaryFire30.h \
    spriteData/sanctuaryOverlay30.h \
    spriteData/satyr30.h \
    spriteData/scholar30.h \
    spriteData/sculptureStudio30.h \
    spriteData/scylla30.h \
    spriteData/settlers130.h \
    spriteData/settlers230.h \
    spriteData/shellGarden30.h \
    spriteData/shepherd30.h \
    spriteData/shortObelisk30.h \
    spriteData/sick30.h \
    spriteData/silverMiner30.h \
    spriteData/spear30.h \
    spriteData/sphinx30.h \
    spriteData/spring30.h \
    spriteData/stadium30.h \
    spriteData/stadiumOverlays130.h \
    spriteData/stadiumOverlays230.h \
    spriteData/stoneCircle30.h \
    spriteData/storNDist30.h \
    spriteData/stor_bays30.h \
    spriteData/storage30.h \
    spriteData/sundial30.h \
    spriteData/supplies30.h \
    spriteData/tallObelisk30.h \
    spriteData/talos30.h \
    spriteData/taxCollector30.h \
    spriteData/taxOffice30.h \
    spriteData/theater30.h \
    spriteData/theaterOverlay30.h \
    spriteData/theseus30.h \
    spriteData/timberMill30.h \
    spriteData/topiary30.h \
    spriteData/tradeBoat30.h \
    spriteData/trader30.h \
    spriteData/tradingPost30.h \
    spriteData/tradingPostOverlay30.h \
    spriteData/trailer30.h \
    spriteData/transporter30.h \
    spriteData/trireme30.h \
    spriteData/triremeOverlay30.h \
    spriteData/triremeWharf30.h \
    spriteData/triremeWharfOverlay130.h \
    spriteData/triremeWharfOverlay230.h \
    spriteData/trojanHoplite30.h \
    spriteData/trojanHorseman30.h \
    spriteData/trojanSpearthrower30.h \
    spriteData/university30.h \
    spriteData/urchin30.h \
    spriteData/urchinGatherer30.h \
    spriteData/urchinQuay30.h \
    spriteData/urchinUnpackingOverlay30.h \
    spriteData/vendorOverlays30.h \
    spriteData/vine30.h \
    spriteData/waitingOverlay30.h \
    spriteData/wall30.h \
    spriteData/warehouse30.h \
    spriteData/warehouseOverlay30.h \
    spriteData/watchPostOverlay30.h \
    spriteData/watchman30.h \
    spriteData/watchpost30.h \
    spriteData/waterDistributor30.h \
    spriteData/waterPark30.h \
    spriteData/wave30.h \
    spriteData/wineVendor30.h \
    spriteData/wineVendorOverlay30.h \
    spriteData/winery30.h \
    spriteData/wolf30.h \
    spriteData/zeus30.h \
    spriteData/zeusElevationTiles230.h \
    spriteData/zeusElevationTiles2A30.h \
    spriteData/zeusElevationTiles30.h \
    spriteData/zeusGodPortraits30.h \
    spriteData/zeusHerosHall30.h \
    spriteData/zeusLand130.h \
    spriteData/zeusLand330.h \
    spriteData/zeusOverlay30.h \
    spriteData/zeusPortraits30.h \
    spriteData/zeusQuarryTileSet30.h \
    spriteData/zeusSanctuary130.h \
    spriteData/zeusSanctuary230.h \
    spriteData/zeusSanctuary330.h \
    spriteData/zeusSanctuaryElements30.h \
    spriteData/zeusStairs30.h \
    spriteData/zeusStatue30.h \
    spriteData/zeusTrees30.h \
    textures/beach-to-dry.h \
    textures/building-textures.h \
    textures/character-textures.h \
    textures/destruction-textures.h \
    textures/fertile-to-dry.h \
    textures/forest-to-dry.h \
    textures/game-textures.h \
    textures/god-textures.h \
    textures/interface-textures.h \
    textures/lava-to-dry.h \
    textures/marble-tile.h \
    textures/marsh-to-dry.h \
    textures/park-texture.h \
    textures/sprite-loader.h \
    textures/stones-to-dry.h \
    textures/surrounding-terrain.h \
    textures/terrain-textures.h \
    textures/tile-to-texture.h \
    textures/varying-size-tex.h \
    textures/water-corner.h \
    textures/water-to-beach.h \
    textures/water-to-dry.h \
    textures/water-to-x.h \
    vec2.h \
    widgets/datawidgets/eadmindatawidget.h \
    widgets/datawidgets/eappealdatawidget.h \
    widgets/datawidgets/eculturedatawidget.h \
    widgets/datawidgets/edatawidget.h \
    widgets/datawidgets/eemploymentdatawidget.h \
    widgets/datawidgets/ehusbandrydatawidget.h \
    widgets/datawidgets/ehygienesafetydatawidget.h \
    widgets/datawidgets/emilitarydatawidget.h \
    widgets/datawidgets/emythologydatawidget.h \
    widgets/datawidgets/e-overview-data-widget.h \
    widgets/datawidgets/population-data-widget.h \
    widgets/datawidgets/esciencedatawidget.h \
    widgets/datawidgets/storage-sidebar-panel.h \
    widgets/datawidgets/eviewmodebutton.h \
    widgets/eacceptbutton.h \
    widgets/eactionlistwidget.h \
    widgets/earmymenu.h \
    widgets/ebasicbutton.h \
    widgets/ebitmapwidget.h \
    widgets/BoardCityswitchbutton.h \
    widgets/eboardsettingsmenu.h \
    widgets/ebuildbutton.h \
    widgets/ebuildingmode.h \
    widgets/ebuildingstoerase.h \
    widgets/ebuildwidget.h \
    widgets/ebutton.h \
    widgets/ebuttonbase.h \
    widgets/ebuttonslistwidget.h \
    widgets/ecancelbutton.h \
    widgets/echeckablebutton.h \
    widgets/echeckbox.h \
    widgets/echoosebutton.h \
    widgets/echoosecitydialog.h \
    widgets/echoosegameeditmenu.h \
    widgets/ecitybutton.h \
    widgets/ecityonboardselectionwidget.h \
    widgets/ecitysettingswidget.h \
    widgets/eclosabledialog.h \
    widgets/condition-settings-widget.h \
    widgets/edatebutton.h \
    widgets/edatewidget.h \
    widgets/district-conditions-widget.h \
    widgets/edownbutton.h \
    widgets/eeditormainmenu.h \
    widgets/eeditorsettingsmenu.h \
    widgets/eenlistforcesdialog.h \
    widgets/eepisodegoalselectionwidget.h \
    widgets/eepisodegoalwidget.h \
    widgets/eepisodeintroductionwidget.h \
    widgets/eepisodelostwidget.h \
    widgets/eepisodeswidget.h \
    widgets/eeventbackground.h \
    widgets/eeventselectionwidget.h \
    widgets/eeventwidget.h \
    widgets/eexclamationbutton.h \
    widgets/eloadgame.h \
    widgets/eflatbutton.h \
    widgets/efonts.h \
    widgets/eframedbutton.h \
    widgets/eframedbuttonwithicon.h \
    widgets/eframedlabel.h \
    widgets/eframedwidget.h \
    widgets/epopupwidget.h \
    widgets/efulfilldialog.h \
    widgets/egameloadingwidget.h \
    widgets/egamemainmenu.h \
    widgets/edifficultywidget.h \
    widgets/game-menu.h \
    widgets/game-menu-base.h \
    widgets/game-widget.h \
    widgets/epierdebugwidget.h \
    widgets/egiftdialog.h \
    widgets/egiftsizedialog.h \
    widgets/egodbutton.h \
    widgets/egodselectionwidget.h \
    widgets/ehelpbutton.h \
    widgets/eherobutton.h \
    widgets/elabel.h \
    widgets/elabelbase.h \
    widgets/elabeledwidget.h \
    widgets/eleftbutton.h \
    widgets/elineedit.h \
    widgets/elinewidget.h \
    widgets/eloadingwidget.h \
    widgets/emainmenu.h \
    widgets/emainmenubase.h \
    widgets/emainwidget.h \
    widgets/emenuloadingwidget.h \
    widgets/e-message-box.h \
    widgets/emessagewidget.h \
    widgets/emicrobutton.h \
    widgets/emilitarymoreinfowidget.h \
    widgets/eminimap.h \
    widgets/emonsterbutton.h \
    widgets/emonsterselectionwidget.h \
    widgets/emouseevent.h \
    widgets/emultilinelabel.h \
    widgets/emultipleselectionwidget.h \
    widgets/enamewidget.h \
    widgets/enumlineedit.h \
    widgets/enumlineeditwidget.h \
    widgets/eokbutton.h \
    widgets/epainter.h \
    widgets/eproceedbutton.h \
    widgets/eprogressbar.h \
    widgets/epyramidbutton.h \
    widgets/epyramidselectionwidget.h \
    widgets/epyramidwidget.h \
    widgets/equestionwidget.h \
    widgets/erequestdialog.h \
    widgets/eresolution.h \
    widgets/eresourcebutton.h \
    widgets/erightbutton.h \
    widgets/erosterofleaders.h \
    widgets/erotatebutton.h \
    widgets/escrollbar.h \
    widgets/escrollbuttonslist.h \
    widgets/escrollwidget.h \
    widgets/escrollwidgetcomplete.h \
    widgets/eselectcolonywidget.h \
    widgets/esmalldownbutton.h \
    widgets/esmallupbutton.h \
    widgets/espinbox.h \
    widgets/eswitchbutton.h \
    widgets/etabwidget.h \
    widgets/eterraineditmenu.h \
    widgets/etextscroller.h \
    widgets/etilepainter.h \
    widgets/etopbarwidget.h \
    widgets/etradeeditwidget.h \
    widgets/etriggerselectionwidget.h \
    widgets/etypebutton.h \
    widgets/eupbutton.h \
    widgets/evaluebutton.h \
    widgets/eventwidgets/eeventwidgetbase.h \
    widgets/eventwidgets/egodattackeventwidget.h \
    widgets/eventwidgets/egoddisastereventwidget.h \
    widgets/eventwidgets/egodquesteventwidget.h \
    widgets/eventwidgets/einvasioneventwidget.h \
    widgets/eviewmode.h \
    widgets/ewatertradewidget.h \
    widgets/ewidget.h \
    widgets/eworldgoodswidget.h \
    widgets/eworldmapwidget.h \
    widgets/eworldmenu.h \
    widgets/eworldtributewidget.h \
    widgets/eworldwidget.h \
    widgets/infowidgets/eagorainfowidget.h \
    widgets/infowidgets/echaracterinfowidget.h \
    widgets/infowidgets/common-house-info-widget.h \
    widgets/infowidgets/eemployingbuildinginfowidget.h \
    widgets/infowidgets/eheroshallinfowidget.h \
    widgets/infowidgets/ehippodromeinfowidget.h \
    widgets/infowidgets/einfowidget.h \
    widgets/infowidgets/esanctuaryinfowidget.h \
    widgets/infowidgets/storage-info-widget.h \
    widgets/infowidgets/trade-post-info-widget.h \
    widgets/infowidgets/etriremewharfinfowidget.h \
    widgets/moreinfo/ecityfinanceswidget.h \
    widgets/moreinfo/eworkforceallocationwidget.h \
    widgets/moreinfo/storage-distribution-dialog.h \

DISTFILES += \
    Adventures/The Founding of Athens/The Founding of Athens.epak \
    Adventures/The Founding of Athens/The Founding of Athens.txt \
    sanctuaries/aphrodite.txt \
    sanctuaries/apollo.txt \
    sanctuaries/ares.txt \
    sanctuaries/artemis.txt \
    sanctuaries/athena.txt \
    sanctuaries/atlas.txt \
    sanctuaries/demeter.txt \
    sanctuaries/dionysus.txt \
    sanctuaries/hades.txt \
    sanctuaries/hephaestus.txt \
    sanctuaries/hera.txt \
    sanctuaries/hermes.txt \
    sanctuaries/poseidon.txt \
    sanctuaries/zeus.txt \
    text/language.txt \
    textureTemplates/achilles \
    textureTemplates/actor \
    textureTemplates/agora \
    textureTemplates/altarBullOverlay \
    textureTemplates/altarGoodsOverlay \
    textureTemplates/altarSheepOverlay \
    textureTemplates/amazonArcher \
    textureTemplates/amazonSpear \
    textureTemplates/aphrodite \
    textureTemplates/aphroditeStatue \
    textureTemplates/apollo \
    textureTemplates/apolloStatue \
    textureTemplates/archer \
    textureTemplates/archerPoseidon \
    textureTemplates/ares \
    textureTemplates/aresStatue \
    textureTemplates/aresWarrior \
    textureTemplates/armory \
    textureTemplates/armsVendor \
    textureTemplates/arrow \
    textureTemplates/artemis \
    textureTemplates/artemisStatue \
    textureTemplates/artisan \
    textureTemplates/artisansGuild \
    textureTemplates/astronomer \
    textureTemplates/atalanta \
    textureTemplates/athena \
    textureTemplates/athenaStatue \
    textureTemplates/atlanteanArcher \
    textureTemplates/atlanteanChariot \
    textureTemplates/atlanteanHoplite \
    textureTemplates/atlas \
    textureTemplates/atlasStatue \
    textureTemplates/avenue \
    textureTemplates/banners \
    textureTemplates/baths \
    textureTemplates/bellerophon \
    textureTemplates/bench \
    textureTemplates/bibliotheke \
    textureTemplates/birdBath \
    textureTemplates/blackArrow \
    textureTemplates/blackMarbleTerrain \
    textureTemplates/blackMarbleTrailer \
    textureTemplates/blackMarbleWorkshop \
    textureTemplates/blackSpear \
    textureTemplates/blankStatue \
    textureTemplates/bless \
    textureTemplates/blessed \
    textureTemplates/boar \
    textureTemplates/bridge \
    textureTemplates/bronzeMiner \
    textureTemplates/bull \
    textureTemplates/butcher \
    textureTemplates/calydonianBoar \
    textureTemplates/cardingShed \
    textureTemplates/cart \
    textureTemplates/cattle1 \
    textureTemplates/cattle2 \
    textureTemplates/cattle3 \
    textureTemplates/centaurArcher \
    textureTemplates/centaurHorseman \
    textureTemplates/cerberus \
    textureTemplates/chariot \
    textureTemplates/chariotFactory \
    textureTemplates/chariotFactoryHorses \
    textureTemplates/chariotFactoryOverlay1 \
    textureTemplates/chariotPoseidon \
    textureTemplates/chariotVendor \
    textureTemplates/chariotVendorCharacter \
    textureTemplates/chariotVendorOverlay \
    textureTemplates/chimera \
    textureTemplates/college \
    textureTemplates/columns \
    textureTemplates/commemorative \
    textureTemplates/commonHouse \
    textureTemplates/competitor \
    textureTemplates/corral \
    textureTemplates/corralCattleOverlay \
    textureTemplates/corralProcessingOverlay \
    textureTemplates/curator \
    textureTemplates/curse \
    textureTemplates/cursed \
    textureTemplates/cyclops \
    textureTemplates/dairy \
    textureTemplates/deer \
    textureTemplates/deerHunter \
    textureTemplates/deerTop \
    textureTemplates/demeter \
    textureTemplates/demeterStatue \
    textureTemplates/dionysus \
    textureTemplates/dionysusStatue \
    textureTemplates/disgruntled \
    textureTemplates/dolphinSculpture \
    textureTemplates/donkey \
    textureTemplates/dragon \
    textureTemplates/dramaSchool \
    textureTemplates/dust \
    textureTemplates/echidna \
    textureTemplates/egyptianArcher \
    textureTemplates/egyptianChariot \
    textureTemplates/egyptianHoplite \
    textureTemplates/elephant \
    textureTemplates/eliteCitizen \
    textureTemplates/eliteHouse \
    textureTemplates/empireBits \
    textureTemplates/empireFigures \
    textureTemplates/enemyBoat \
    textureTemplates/fire1 \
    textureTemplates/fireFighter \
    textureTemplates/fish \
    textureTemplates/fishPond \
    textureTemplates/fishPondOverlay \
    textureTemplates/fishery \
    textureTemplates/fisheryBoatBuilding \
    textureTemplates/fisheryOverlay \
    textureTemplates/fisheryUnpackingOverlay \
    textureTemplates/fishingBoat \
    textureTemplates/fleeceVendor \
    textureTemplates/fleecedSheep \
    textureTemplates/flowerGarden \
    textureTemplates/foodCart \
    textureTemplates/foodVendor \
    textureTemplates/foundry \
    textureTemplates/fountain \
    textureTemplates/gatehouseAndTower \
    textureTemplates/gazebo \
    textureTemplates/goat \
    textureTemplates/goatherd \
    textureTemplates/godBlueArrow \
    textureTemplates/godBlueMissile \
    textureTemplates/godGreenMissile \
    textureTemplates/godOrangeArrow \
    textureTemplates/godOrangeMissile \
    textureTemplates/godPinkMissile \
    textureTemplates/godPurpleMissile \
    textureTemplates/godRedMissile \
    textureTemplates/granary \
    textureTemplates/greekHoplite \
    textureTemplates/greekHorseman \
    textureTemplates/greekRockThrower \
    textureTemplates/grower \
    textureTemplates/growersLodge \
    textureTemplates/gymnasium \
    textureTemplates/gymnast \
    textureTemplates/hades \
    textureTemplates/hadesStatue \
    textureTemplates/harpie \
    textureTemplates/healer \
    textureTemplates/hector \
    textureTemplates/hedgeMaze \
    textureTemplates/hephaestus \
    textureTemplates/hephaestusStatue \
    textureTemplates/hera \
    textureTemplates/heraStatue \
    textureTemplates/heracles \
    textureTemplates/hermes \
    textureTemplates/hermesStatue \
    textureTemplates/hippodrome \
    textureTemplates/hippodromeBeer \
    textureTemplates/hippodromeFeces \
    textureTemplates/hippodromeFinish \
    textureTemplates/hippodromeHorse1 \
    textureTemplates/hippodromeHorse2 \
    textureTemplates/hippodromeHorse3 \
    textureTemplates/hippodromeHorse4 \
    textureTemplates/hippodromeHotDogs \
    textureTemplates/hippodromeSpectators \
    textureTemplates/hippodromeStand \
    textureTemplates/homeless \
    textureTemplates/hoplite \
    textureTemplates/hoplitePoseidon \
    textureTemplates/horse \
    textureTemplates/horseRanch \
    textureTemplates/horseRanchEnclosure \
    textureTemplates/horseVendor \
    textureTemplates/horseman \
    textureTemplates/hospital \
    textureTemplates/hunter \
    textureTemplates/huntingLodge \
    textureTemplates/hydra \
    textureTemplates/interfaceBanners \
    textureTemplates/interfaceMapEditor \
    textureTemplates/interfaceNewBbuttons \
    textureTemplates/interfaceNewParts \
    textureTemplates/interfaceParts \
    textureTemplates/interfaceRadar \
    textureTemplates/interfaceSprites \
    textureTemplates/interfaceWorldSide \
    textureTemplates/interface_stor_bays \
    textureTemplates/inventor \
    textureTemplates/inventorsWorkshop \
    textureTemplates/jason \
    textureTemplates/kraken \
    textureTemplates/laboratory \
    textureTemplates/lava \
    textureTemplates/lumberjack \
    textureTemplates/maenads \
    textureTemplates/maintenanceOffice \
    textureTemplates/marbleMiner \
    textureTemplates/masonryShop \
    textureTemplates/masonryShopOverlays \
    textureTemplates/mayanArcher \
    textureTemplates/mayanHoplite \
    textureTemplates/medusa \
    textureTemplates/minotaur \
    textureTemplates/mint \
    textureTemplates/monsterMissile \
    textureTemplates/mun_Palace \
    textureTemplates/museum \
    textureTemplates/nudeSheep \
    textureTemplates/observatory \
    textureTemplates/oceanidHoplite \
    textureTemplates/oceanidSpearthrower \
    textureTemplates/odysseus \
    textureTemplates/oilVendor \
    textureTemplates/olivePress \
    textureTemplates/oliveTree \
    textureTemplates/orangeTender \
    textureTemplates/orangeTendersLodge \
    textureTemplates/orangesCart \
    textureTemplates/orichalcArcher \
    textureTemplates/orichalcCart \
    textureTemplates/orichalcExplosion \
    textureTemplates/orichalcMiner \
    textureTemplates/orichalcMissile \
    textureTemplates/orichalcTerrain \
    textureTemplates/orichalcTowerOverlay \
    textureTemplates/orrery \
    textureTemplates/ox \
    textureTemplates/oxHandler \
    textureTemplates/palaceOverlay \
    textureTemplates/palaceTiles \
    textureTemplates/paneling \
    textureTemplates/park \
    textureTemplates/peddler \
    textureTemplates/perseus \
    textureTemplates/persianArcher \
    textureTemplates/persianHoplite \
    textureTemplates/persianHorseman \
    textureTemplates/philosopher \
    textureTemplates/phoenicianArcher \
    textureTemplates/phoenicianHorseman \
    textureTemplates/pier1 \
    textureTemplates/pier2 \
    textureTemplates/pierOverlay \
    textureTemplates/plague \
    textureTemplates/plantation \
    textureTemplates/podium \
    textureTemplates/porter \
    textureTemplates/poseidon \
    textureTemplates/poseidonBannerTops \
    textureTemplates/poseidonBridge \
    textureTemplates/poseidonCampaign1 \
    textureTemplates/poseidonCampaign2 \
    textureTemplates/poseidonCampaign3 \
    textureTemplates/poseidonCampaign4 \
    textureTemplates/poseidonCampaign5 \
    textureTemplates/poseidonCampaign6 \
    textureTemplates/poseidonCommonHouse \
    textureTemplates/poseidonEliteHouse \
    textureTemplates/poseidonHerosHall \
    textureTemplates/poseidonHerosHall2 \
    textureTemplates/poseidonInterface \
    textureTemplates/poseidonPortraits \
    textureTemplates/poseidonPyramid \
    textureTemplates/poseidonPyramid2 \
    textureTemplates/poseidonQuestButtons \
    textureTemplates/poseidonSanctuary \
    textureTemplates/poseidonStatue \
    textureTemplates/poseidonStatues1 \
    textureTemplates/poseidonStatues2 \
    textureTemplates/poseidonTowerArcher \
    textureTemplates/poseidonTrees \
    textureTemplates/poseidonUnits \
    textureTemplates/priest \
    textureTemplates/refinery \
    textureTemplates/roadblock \
    textureTemplates/rock \
    textureTemplates/rockThrower \
    textureTemplates/sanctuaryFire \
    textureTemplates/sanctuaryOverlay \
    textureTemplates/satyr \
    textureTemplates/scholar \
    textureTemplates/sculptureStudio \
    textureTemplates/scylla \
    textureTemplates/settlers1 \
    textureTemplates/settlers2 \
    textureTemplates/shellGarden \
    textureTemplates/shepherd \
    textureTemplates/shortObelisk \
    textureTemplates/sick \
    textureTemplates/silverMiner \
    textureTemplates/spear \
    textureTemplates/sphinx \
    textureTemplates/spring \
    textureTemplates/stadium \
    textureTemplates/stadiumOverlays1 \
    textureTemplates/stadiumOverlays2 \
    textureTemplates/stoneCircle \
    textureTemplates/stor_bays \
    textureTemplates/storage \
    textureTemplates/sundial \
    textureTemplates/supplies \
    textureTemplates/tallObelisk \
    textureTemplates/talos \
    textureTemplates/taxCollector \
    textureTemplates/taxOffice \
    textureTemplates/theater \
    textureTemplates/theaterOverlay \
    textureTemplates/theseus \
    textureTemplates/timberMill \
    textureTemplates/topiary \
    textureTemplates/tradeBoat \
    textureTemplates/trader \
    textureTemplates/tradingPost \
    textureTemplates/tradingPostOverlay \
    textureTemplates/trailer \
    textureTemplates/transporter \
    textureTemplates/trireme \
    textureTemplates/triremeOverlay \
    textureTemplates/triremeWharf \
    textureTemplates/triremeWharfOverlay1 \
    textureTemplates/triremeWharfOverlay2 \
    textureTemplates/trojanHoplite \
    textureTemplates/trojanHorseman \
    textureTemplates/trojanSpearthrower \
    textureTemplates/university \
    textureTemplates/urchin \
    textureTemplates/urchinGatherer \
    textureTemplates/urchinQuay \
    textureTemplates/urchinUnpackingOverlay \
    textureTemplates/vendorOverlays \
    textureTemplates/vine \
    textureTemplates/waitingOverlay \
    textureTemplates/wall \
    textureTemplates/warehouse \
    textureTemplates/warehouseOverlay \
    textureTemplates/watchPostOverlay \
    textureTemplates/watchman \
    textureTemplates/watchpost \
    textureTemplates/waterDistributor \
    textureTemplates/waterPark \
    textureTemplates/wave \
    textureTemplates/wineVendor \
    textureTemplates/wineVendorOverlay \
    textureTemplates/winery \
    textureTemplates/wolf \
    textureTemplates/zeus \
    textureTemplates/zeusElevationTiles \
    textureTemplates/zeusElevationTiles2 \
    textureTemplates/zeusElevationTiles2A \
    textureTemplates/zeusGodPortraits \
    textureTemplates/zeusHerosHall \
    textureTemplates/zeusLand1 \
    textureTemplates/zeusLand3 \
    textureTemplates/zeusOverlay \
    textureTemplates/zeusPortraits \
    textureTemplates/zeusQuarryTileSet \
    textureTemplates/zeusSanctuary1 \
    textureTemplates/zeusSanctuary2 \
    textureTemplates/zeusSanctuary3 \
    textureTemplates/zeusSanctuaryElements \
    textureTemplates/zeusStairs \
    textureTemplates/zeusStatue \
    textureTemplates/zeusTrees
