#include "stamp-template-writer.h"

#include "buildings/ebuilding.h"

#include <filesystem>
#include <fstream>

const char* eStampBuildingTypeName(const eBuildingType type) {
    switch(type) {
#define STAMP_TYPE(TYPE) case eBuildingType::TYPE: return #TYPE;
    STAMP_TYPE(none)
    STAMP_TYPE(erase)
    STAMP_TYPE(road)
    STAMP_TYPE(commonHouse)
    STAMP_TYPE(eliteHousing)
    STAMP_TYPE(gymnasium)
    STAMP_TYPE(college)
    STAMP_TYPE(dramaSchool)
    STAMP_TYPE(podium)
    STAMP_TYPE(theater)
    STAMP_TYPE(stadium)
    STAMP_TYPE(bibliotheke)
    STAMP_TYPE(observatory)
    STAMP_TYPE(university)
    STAMP_TYPE(laboratory)
    STAMP_TYPE(inventorsWorkshop)
    STAMP_TYPE(museum)
    STAMP_TYPE(fountain)
    STAMP_TYPE(hospital)
    STAMP_TYPE(goat)
    STAMP_TYPE(sheep)
    STAMP_TYPE(cattle)
    STAMP_TYPE(oliveTree)
    STAMP_TYPE(vine)
    STAMP_TYPE(orangeTree)
    STAMP_TYPE(wheatFarm)
    STAMP_TYPE(carrotsFarm)
    STAMP_TYPE(onionsFarm)
    STAMP_TYPE(huntingLodge)
    STAMP_TYPE(fishery)
    STAMP_TYPE(urchinQuay)
    STAMP_TYPE(cardingShed)
    STAMP_TYPE(dairy)
    STAMP_TYPE(growersLodge)
    STAMP_TYPE(orangeTendersLodge)
    STAMP_TYPE(corral)
    STAMP_TYPE(granary)
    STAMP_TYPE(warehouse)
    STAMP_TYPE(tradePost)
    STAMP_TYPE(pier)
    STAMP_TYPE(commonAgora)
    STAMP_TYPE(grandAgora)
    STAMP_TYPE(agoraSpace)
    STAMP_TYPE(foodVendor)
    STAMP_TYPE(fleeceVendor)
    STAMP_TYPE(oilVendor)
    STAMP_TYPE(wineVendor)
    STAMP_TYPE(armsVendor)
    STAMP_TYPE(horseTrainer)
    STAMP_TYPE(chariotVendor)
    STAMP_TYPE(timberMill)
    STAMP_TYPE(masonryShop)
    STAMP_TYPE(mint)
    STAMP_TYPE(foundry)
    STAMP_TYPE(olivePress)
    STAMP_TYPE(winery)
    STAMP_TYPE(sculptureStudio)
    STAMP_TYPE(artisansGuild)
    STAMP_TYPE(wall)
    STAMP_TYPE(tower)
    STAMP_TYPE(gatehouse)
    STAMP_TYPE(triremeWharf)
    STAMP_TYPE(horseRanch)
    STAMP_TYPE(horseRanchEnclosure)
    STAMP_TYPE(chariotFactory)
    STAMP_TYPE(armory)
    STAMP_TYPE(maintenanceOffice)
    STAMP_TYPE(taxOffice)
    STAMP_TYPE(watchPost)
    STAMP_TYPE(palace)
    STAMP_TYPE(palaceTile)
    STAMP_TYPE(bridge)
    STAMP_TYPE(park)
    STAMP_TYPE(doricColumn)
    STAMP_TYPE(ionicColumn)
    STAMP_TYPE(corinthianColumn)
    STAMP_TYPE(avenue)
    STAMP_TYPE(commemorative)
    STAMP_TYPE(godMonument)
    STAMP_TYPE(godMonumentTile)
    STAMP_TYPE(bench)
    STAMP_TYPE(flowerGarden)
    STAMP_TYPE(gazebo)
    STAMP_TYPE(hedgeMaze)
    STAMP_TYPE(fishPond)
    STAMP_TYPE(waterPark)
    STAMP_TYPE(birdBath)
    STAMP_TYPE(shortObelisk)
    STAMP_TYPE(tallObelisk)
    STAMP_TYPE(shellGarden)
    STAMP_TYPE(sundial)
    STAMP_TYPE(dolphinSculpture)
    STAMP_TYPE(orrery)
    STAMP_TYPE(spring)
    STAMP_TYPE(topiary)
    STAMP_TYPE(baths)
    STAMP_TYPE(stoneCircle)
    STAMP_TYPE(templeAphrodite)
    STAMP_TYPE(templeApollo)
    STAMP_TYPE(templeAres)
    STAMP_TYPE(templeArtemis)
    STAMP_TYPE(templeAthena)
    STAMP_TYPE(templeAtlas)
    STAMP_TYPE(templeDemeter)
    STAMP_TYPE(templeDionysus)
    STAMP_TYPE(templeHades)
    STAMP_TYPE(templeHephaestus)
    STAMP_TYPE(templeHera)
    STAMP_TYPE(templeHermes)
    STAMP_TYPE(templePoseidon)
    STAMP_TYPE(templeZeus)
    STAMP_TYPE(temple)
    STAMP_TYPE(templeTile)
    STAMP_TYPE(templeStatue)
    STAMP_TYPE(templeMonument)
    STAMP_TYPE(templeAltar)
    STAMP_TYPE(achillesHall)
    STAMP_TYPE(atalantaHall)
    STAMP_TYPE(bellerophonHall)
    STAMP_TYPE(herculesHall)
    STAMP_TYPE(jasonHall)
    STAMP_TYPE(odysseusHall)
    STAMP_TYPE(perseusHall)
    STAMP_TYPE(theseusHall)
    STAMP_TYPE(ruins)
    STAMP_TYPE(placeholder)
    STAMP_TYPE(refinery)
    STAMP_TYPE(blackMarbleWorkshop)
    STAMP_TYPE(modestPyramid)
    STAMP_TYPE(pyramid)
    STAMP_TYPE(greatPyramid)
    STAMP_TYPE(majesticPyramid)
    STAMP_TYPE(smallMonumentToTheSky)
    STAMP_TYPE(monumentToTheSky)
    STAMP_TYPE(grandMonumentToTheSky)
    STAMP_TYPE(minorShrineAphrodite)
    STAMP_TYPE(minorShrineApollo)
    STAMP_TYPE(minorShrineAres)
    STAMP_TYPE(minorShrineArtemis)
    STAMP_TYPE(minorShrineAthena)
    STAMP_TYPE(minorShrineAtlas)
    STAMP_TYPE(minorShrineDemeter)
    STAMP_TYPE(minorShrineDionysus)
    STAMP_TYPE(minorShrineHades)
    STAMP_TYPE(minorShrineHephaestus)
    STAMP_TYPE(minorShrineHera)
    STAMP_TYPE(minorShrineHermes)
    STAMP_TYPE(minorShrinePoseidon)
    STAMP_TYPE(minorShrineZeus)
    STAMP_TYPE(shrineAphrodite)
    STAMP_TYPE(shrineApollo)
    STAMP_TYPE(shrineAres)
    STAMP_TYPE(shrineArtemis)
    STAMP_TYPE(shrineAthena)
    STAMP_TYPE(shrineAtlas)
    STAMP_TYPE(shrineDemeter)
    STAMP_TYPE(shrineDionysus)
    STAMP_TYPE(shrineHades)
    STAMP_TYPE(shrineHephaestus)
    STAMP_TYPE(shrineHera)
    STAMP_TYPE(shrineHermes)
    STAMP_TYPE(shrinePoseidon)
    STAMP_TYPE(shrineZeus)
    STAMP_TYPE(majorShrineAphrodite)
    STAMP_TYPE(majorShrineApollo)
    STAMP_TYPE(majorShrineAres)
    STAMP_TYPE(majorShrineArtemis)
    STAMP_TYPE(majorShrineAthena)
    STAMP_TYPE(majorShrineAtlas)
    STAMP_TYPE(majorShrineDemeter)
    STAMP_TYPE(majorShrineDionysus)
    STAMP_TYPE(majorShrineHades)
    STAMP_TYPE(majorShrineHephaestus)
    STAMP_TYPE(majorShrineHera)
    STAMP_TYPE(majorShrineHermes)
    STAMP_TYPE(majorShrinePoseidon)
    STAMP_TYPE(majorShrineZeus)
    STAMP_TYPE(pyramidOfThePantheon)
    STAMP_TYPE(altarOfOlympus)
    STAMP_TYPE(templeOfOlympus)
    STAMP_TYPE(observatoryKosmika)
    STAMP_TYPE(museumAtlantika)
    STAMP_TYPE(pyramidPart)
    STAMP_TYPE(pyramidWall)
    STAMP_TYPE(pyramidTop)
    STAMP_TYPE(pyramidStatue)
    STAMP_TYPE(pyramidMonument)
    STAMP_TYPE(pyramidTile)
    STAMP_TYPE(pyramidAltar)
    STAMP_TYPE(pyramidTemple)
    STAMP_TYPE(pyramidObservatory)
    STAMP_TYPE(pyramidMuseum)
    STAMP_TYPE(hippodromePiece)
    STAMP_TYPE(crosswalk)
    STAMP_TYPE(roadblock)
#undef STAMP_TYPE
    }
    return nullptr;
}

bool eWriteStampTemplate(const std::string& path,
                         const std::vector<eStampElement>& blueprint) {
    const std::filesystem::path outPath(path);
    const auto parent = outPath.parent_path();
    if(!parent.empty()) {
        std::error_code ec;
        std::filesystem::create_directories(parent, ec);
        if(ec) return false;
    }

    std::ofstream file(path);
    if(!file.good()) return false;

    file << "{\n";
    for(const auto& elem : blueprint) {
        const auto typeName = eStampBuildingTypeName(elem.type);
        if(!typeName) return false;
        file << "    {eBuildingType::" << typeName << ", "
             << elem.dx << ", " << elem.dy;
        if(elem.id >= 0) file << ", " << elem.id;
        file << "},\n";
    }
    file << "}\n";
    return file.good();
}
