#include "estampblueprint.h"

#include "buildings/ebuilding.h"

std::vector<eStampElement> eDefaultStampBlueprint()
{
    // Blueprint from HTML table, using top-left cells for multi-tile buildings.
    return {
        {eBuildingType::road, 0, 0},
        {eBuildingType::road, 1, 0},
        {eBuildingType::road, 2, 0},
        {eBuildingType::road, 3, 0},
        {eBuildingType::road, 4, 0},
        {eBuildingType::road, 5, 0},
        {eBuildingType::road, 6, 0},
        {eBuildingType::road, 7, 0},
        {eBuildingType::roadblock, 0, 1},
        {eBuildingType::foodVendor, 1, 1},
        {eBuildingType::fleeceVendor, 3, 1},
        {eBuildingType::oilVendor, 5, 1},
        {eBuildingType::roadblock, 7, 1},
        {eBuildingType::road, 0, 2},
        {eBuildingType::road, 7, 2},
        {eBuildingType::road, 0, 3},
        {eBuildingType::granary, 1, 3},
        {eBuildingType::maintenanceOffice, 5, 3},
        {eBuildingType::road, 7, 3},
        {eBuildingType::road, 0, 4},
        {eBuildingType::road, 7, 4},
        {eBuildingType::road, 0, 5},
        {eBuildingType::park, 5, 5},
        {eBuildingType::park, 6, 5},
        {eBuildingType::park, 5, 6},
        {eBuildingType::park, 6, 6},
        {eBuildingType::road, 7, 5},
        {eBuildingType::road, 0, 6},
        {eBuildingType::road, 7, 6},
        {eBuildingType::road, 0, 7},
        {eBuildingType::warehouse, 1, 7},
        {eBuildingType::warehouse, 4, 7},
        {eBuildingType::road, 7, 7},
        {eBuildingType::road, 0, 8},
        {eBuildingType::road, 7, 8},
        {eBuildingType::road, 0, 9},
        {eBuildingType::road, 7, 9},
        {eBuildingType::road, 0, 10},
        {eBuildingType::warehouse, 1, 10},
        {eBuildingType::warehouse, 4, 10},
        {eBuildingType::road, 7, 10},
        {eBuildingType::road, 0, 11},
        {eBuildingType::road, 7, 11},
        {eBuildingType::road, 0, 12},
        {eBuildingType::road, 7, 12},
        {eBuildingType::road, 0, 13},
        {eBuildingType::park, 1, 13},
        {eBuildingType::park, 2, 13},
        {eBuildingType::park, 1, 14},
        {eBuildingType::park, 2, 14},
        {eBuildingType::granary, 3, 13},
        {eBuildingType::road, 7, 13},
        {eBuildingType::road, 0, 14},
        {eBuildingType::road, 7, 14},
        {eBuildingType::road, 0, 15},
        {eBuildingType::maintenanceOffice, 1, 15},
        {eBuildingType::road, 7, 15},
        {eBuildingType::roadblock, 0, 16},
        {eBuildingType::roadblock, 7, 16},
        {eBuildingType::road, 0, 17},
        {eBuildingType::road, 1, 17},
        {eBuildingType::road, 2, 17},
        {eBuildingType::road, 3, 17},
        {eBuildingType::road, 4, 17},
        {eBuildingType::road, 5, 17},
        {eBuildingType::road, 6, 17},
        {eBuildingType::road, 7, 17}

    };
}
